PROMPT Creating rescue 14/15/16 indexes...

-- 加快提醒中心按发送状态和提醒时间查询的速度。
DECLARE
BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_MED_REMINDERS_STATUS_TIME ON MED_REMINDERS(SENDSTATUS, REMINDERTIME)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

-- 加快猫咪详情页按猫查询提醒历史的速度。
DECLARE
BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_MED_REMINDERS_CAT ON MED_REMINDERS(CATID)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

-- 加快管理员按处理状态和紧急等级筛选紧急上报的速度。
DECLARE
BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_EMERGENCY_STATUS_LEVEL ON EMERGENCY_REPORTS(PROCESSSTATUS, URGENCYLEVEL)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

-- 加快按处理人查看紧急上报任务的速度。
DECLARE
BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_EMERGENCY_HANDLER ON EMERGENCY_REPORTS(HANDLERUSERID)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

-- 加快按失踪预警状态筛选处理列表的速度。
DECLARE
BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_MISSING_STATUS ON CAT_MISSINGALERTS(ALERTSTATUS)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

-- 加快按猫咪和预警状态查询失踪预警历史的速度。
DECLARE
BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_MISSING_CAT_STATUS ON CAT_MISSINGALERTS(CATID, ALERTSTATUS)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/
