PROMPT Creating rescue 14/15/16 views...

-- 医疗提醒完整视图：Repository 按猫查询和按 ID 回查时使用。
CREATE OR REPLACE VIEW V_MED_REMINDERS AS
SELECT R.REMINDERID,
       R.RECORDID,
       R.CATID,
       C.CATNAME,
       R.REMINDERTYPE,
       R.RECEIVERUSERID,
       U.USERNAME AS RECEIVERUSERNAME,
       R.REMINDERTIME,
       NVL(R.SENDSTATUS, 'PENDING') AS SENDSTATUS
FROM MED_REMINDERS R
LEFT JOIN CAT_CATS C ON R.CATID = C.CATID
LEFT JOIN SYS_USERS U ON R.RECEIVERUSERID = U.USERID;

-- 待处理提醒视图：Repository 的提醒中心列表接口使用。
CREATE OR REPLACE VIEW V_MED_PENDING_REMINDERS AS
SELECT REMINDERID,
       RECORDID,
       CATID,
       CATNAME,
       REMINDERTYPE,
       RECEIVERUSERID,
       RECEIVERUSERNAME,
       REMINDERTIME,
       SENDSTATUS
FROM V_MED_REMINDERS
WHERE SENDSTATUS IN ('PENDING', 'SENT');

-- 紧急上报视图：Repository 查询全部和按 ID 查询时使用。
CREATE OR REPLACE VIEW V_EMERGENCY_REPORTS AS
SELECT E.REPORTID,
       E.REPORTERUSERID,
       RU.USERNAME AS REPORTERUSERNAME,
       E.AREAID,
       A.AREANAME,
       E.ANIMALTYPE,
       E.PHOTOURL,
       E.LONGITUDE,
       E.LATITUDE,
       E.REPORTTIME,
       E.URGENCYLEVEL,
       E.PROCESSSTATUS,
       E.HANDLERUSERID,
       HU.USERNAME AS HANDLERUSERNAME,
       E.PROCESSRESULT
FROM EMERGENCY_REPORTS E
LEFT JOIN SYS_USERS RU ON E.REPORTERUSERID = RU.USERID
LEFT JOIN SYS_USERS HU ON E.HANDLERUSERID = HU.USERID
LEFT JOIN MAP_CAMPUSAREAS A ON E.AREAID = A.AREAID;

-- 失踪预警视图：Repository 查询全部、按猫查询和按 ID 回查时使用。
CREATE OR REPLACE VIEW V_MISSING_ALERTS AS
SELECT M.ALERTID,
       M.CATID,
       C.CATNAME,
       M.LASTSIGHTINGID,
       S.AREAID AS LASTSIGHTINGAREAID,
       A.AREANAME AS LASTSIGHTINGAREANAME,
       M.LASTSIGHTINGTIME,
       M.THRESHOLDDAYS,
       M.ALERTTIME,
       M.ALERTSTATUS,
       M.HANDLERUSERID,
       U.USERNAME AS HANDLERUSERNAME,
       M.CLOSETIME,
       M.REMARK
FROM CAT_MISSINGALERTS M
LEFT JOIN CAT_CATS C ON M.CATID = C.CATID
LEFT JOIN CAT_SIGHTINGS S ON M.LASTSIGHTINGID = S.SIGHTINGID
LEFT JOIN MAP_CAMPUSAREAS A ON S.AREAID = A.AREAID
LEFT JOIN SYS_USERS U ON M.HANDLERUSERID = U.USERID;
