PROMPT Creating rescue 14/15/16 triggers...

-- 医疗提醒插入前触发器：补 ID，并统一提醒类型和发送状态。
CREATE OR REPLACE TRIGGER TRG_MED_REMINDERS_BI
BEFORE INSERT ON MED_REMINDERS
FOR EACH ROW
BEGIN
    IF :NEW.REMINDERID IS NULL THEN
        :NEW.REMINDERID := LOWER(RAWTOHEX(SYS_GUID()));
    END IF;

    :NEW.REMINDERTYPE := UPPER(:NEW.REMINDERTYPE);
    :NEW.SENDSTATUS := UPPER(NVL(:NEW.SENDSTATUS, 'PENDING'));
END;
/

-- 医疗提醒更新前触发器：防止大小写不一致影响查询。
CREATE OR REPLACE TRIGGER TRG_MED_REMINDERS_BU
BEFORE UPDATE ON MED_REMINDERS
FOR EACH ROW
BEGIN
    :NEW.REMINDERTYPE := UPPER(:NEW.REMINDERTYPE);
    :NEW.SENDSTATUS := UPPER(:NEW.SENDSTATUS);
END;
/

-- 紧急上报插入前触发器：补 ID、上报时间、默认状态，并统一枚举大小写。
CREATE OR REPLACE TRIGGER TRG_EMERGENCY_REPORTS_BI
BEFORE INSERT ON EMERGENCY_REPORTS
FOR EACH ROW
BEGIN
    IF :NEW.REPORTID IS NULL THEN
        :NEW.REPORTID := LOWER(RAWTOHEX(SYS_GUID()));
    END IF;

    IF :NEW.REPORTTIME IS NULL THEN
        :NEW.REPORTTIME := SYSDATE;
    END IF;

    :NEW.URGENCYLEVEL := UPPER(NVL(:NEW.URGENCYLEVEL, 'LOW'));
    :NEW.PROCESSSTATUS := UPPER(NVL(:NEW.PROCESSSTATUS, 'SUBMITTED'));
END;
/

-- 紧急上报更新前触发器：统一紧急等级和处理状态大小写。
CREATE OR REPLACE TRIGGER TRG_EMERGENCY_REPORTS_BU
BEFORE UPDATE ON EMERGENCY_REPORTS
FOR EACH ROW
BEGIN
    IF :NEW.URGENCYLEVEL IS NOT NULL THEN
        :NEW.URGENCYLEVEL := UPPER(:NEW.URGENCYLEVEL);
    END IF;

    IF :NEW.PROCESSSTATUS IS NOT NULL THEN
        :NEW.PROCESSSTATUS := UPPER(:NEW.PROCESSSTATUS);
    END IF;
END;
/

-- 失踪预警插入前触发器：补 ID、发布时间和默认处理状态。
CREATE OR REPLACE TRIGGER TRG_CAT_MISSINGALERTS_BI
BEFORE INSERT ON CAT_MISSINGALERTS
FOR EACH ROW
BEGIN
    IF :NEW.ALERTID IS NULL THEN
        :NEW.ALERTID := LOWER(RAWTOHEX(SYS_GUID()));
    END IF;

    IF :NEW.ALERTTIME IS NULL THEN
        :NEW.ALERTTIME := SYSDATE;
    END IF;

    :NEW.ALERTSTATUS := UPPER(NVL(:NEW.ALERTSTATUS, 'PROCESSING'));
END;
/

-- 失踪预警更新前触发器：统一状态，并在寻回或关闭时自动补关闭时间。
CREATE OR REPLACE TRIGGER TRG_CAT_MISSINGALERTS_BU
BEFORE UPDATE ON CAT_MISSINGALERTS
FOR EACH ROW
BEGIN
    IF :NEW.ALERTSTATUS IS NOT NULL THEN
        :NEW.ALERTSTATUS := UPPER(:NEW.ALERTSTATUS);
    END IF;

    IF :NEW.ALERTSTATUS IN ('FOUND', 'CLOSED') AND :NEW.CLOSETIME IS NULL THEN
        :NEW.CLOSETIME := SYSDATE;
    END IF;
END;
/

-- 猫咪目击记录插入前触发器：补 ID 和默认目击时间。
CREATE OR REPLACE TRIGGER TRG_CAT_SIGHTINGS_BI
BEFORE INSERT ON CAT_SIGHTINGS
FOR EACH ROW
BEGIN
    IF :NEW.SIGHTINGID IS NULL THEN
        :NEW.SIGHTINGID := LOWER(RAWTOHEX(SYS_GUID()));
    END IF;

    IF :NEW.SIGHTINGTIME IS NULL THEN
        :NEW.SIGHTINGTIME := SYSDATE;
    END IF;
END;
/

-- 医疗记录插入后触发器：疫苗、驱虫、绝育、复查记录有 NEXTDUEDATE 时自动生成提醒。
CREATE OR REPLACE TRIGGER TRG_HEALTHRECORDS_AI_REMINDER
AFTER INSERT ON MED_HEALTHRECORDS
FOR EACH ROW
DECLARE
    V_REMINDERTYPE MED_REMINDERS.REMINDERTYPE%TYPE;
BEGIN
    IF :NEW.NEXTDUEDATE IS NULL THEN
        RETURN;
    END IF;

    V_REMINDERTYPE :=
        CASE UPPER(:NEW.RECORDTYPE)
            WHEN 'VACCINE' THEN 'VACCINE'
            WHEN 'DEWORM' THEN 'DEWORM'
            WHEN 'STERILIZATION' THEN 'STERILIZATION'
            ELSE 'RECHECK'
        END;

    INSERT INTO MED_REMINDERS (
        REMINDERID,
        RECORDID,
        CATID,
        REMINDERTYPE,
        REMINDERTIME,
        SENDSTATUS
    ) VALUES (
        LOWER(RAWTOHEX(SYS_GUID())),
        :NEW.RECORDID,
        :NEW.CATID,
        V_REMINDERTYPE,
        :NEW.NEXTDUEDATE,
        'PENDING'
    );
END;
/
