PROMPT Creating rescue 14/15/16 package specification...

CREATE OR REPLACE PACKAGE PKG_RESCUE_141516 AS
    -- 14. 新增医疗提醒。
    PROCEDURE CREATE_REMINDER(
        P_RECORDID       IN MED_REMINDERS.RECORDID%TYPE,
        P_CATID          IN MED_REMINDERS.CATID%TYPE,
        P_REMINDERTYPE   IN MED_REMINDERS.REMINDERTYPE%TYPE,
        P_RECEIVERUSERID IN MED_REMINDERS.RECEIVERUSERID%TYPE,
        P_REMINDERTIME   IN MED_REMINDERS.REMINDERTIME%TYPE,
        O_REMINDERID     OUT MED_REMINDERS.REMINDERID%TYPE
    );

    -- 14. 标记提醒已经发送。
    PROCEDURE MARK_REMINDER_SENT(P_REMINDERID IN MED_REMINDERS.REMINDERID%TYPE);

    -- 14. 标记提醒已经完成。
    PROCEDURE COMPLETE_REMINDER(P_REMINDERID IN MED_REMINDERS.REMINDERID%TYPE);

    -- 15. 普通用户提交紧急救助上报。
    PROCEDURE SUBMIT_EMERGENCY_REPORT(
        P_REPORTERUSERID IN EMERGENCY_REPORTS.REPORTERUSERID%TYPE,
        P_AREAID         IN EMERGENCY_REPORTS.AREAID%TYPE,
        P_ANIMALTYPE     IN EMERGENCY_REPORTS.ANIMALTYPE%TYPE,
        P_PHOTOURL       IN EMERGENCY_REPORTS.PHOTOURL%TYPE,
        P_LONGITUDE      IN EMERGENCY_REPORTS.LONGITUDE%TYPE,
        P_LATITUDE       IN EMERGENCY_REPORTS.LATITUDE%TYPE,
        P_URGENCYLEVEL   IN EMERGENCY_REPORTS.URGENCYLEVEL%TYPE,
        O_REPORTID       OUT EMERGENCY_REPORTS.REPORTID%TYPE
    );

    -- 15. 管理员或志愿者分配紧急上报处理人。
    PROCEDURE ASSIGN_EMERGENCY_REPORT(
        P_REPORTID      IN EMERGENCY_REPORTS.REPORTID%TYPE,
        P_HANDLERUSERID IN EMERGENCY_REPORTS.HANDLERUSERID%TYPE
    );

    -- 15. 更新紧急上报处理状态和处理结果。
    PROCEDURE UPDATE_EMERGENCY_STATUS(
        P_REPORTID      IN EMERGENCY_REPORTS.REPORTID%TYPE,
        P_PROCESSSTATUS IN EMERGENCY_REPORTS.PROCESSSTATUS%TYPE,
        P_PROCESSRESULT IN EMERGENCY_REPORTS.PROCESSRESULT%TYPE
    );

    -- 16. 创建猫咪目击记录，用于记录最后目击信息。
    PROCEDURE CREATE_SIGHTING(
        P_CATID        IN CAT_SIGHTINGS.CATID%TYPE,
        P_USERID       IN CAT_SIGHTINGS.USERID%TYPE,
        P_AREAID       IN CAT_SIGHTINGS.AREAID%TYPE,
        P_LONGITUDE    IN CAT_SIGHTINGS.LONGITUDE%TYPE,
        P_LATITUDE     IN CAT_SIGHTINGS.LATITUDE%TYPE,
        P_PHOTOURL     IN CAT_SIGHTINGS.PHOTOURL%TYPE,
        P_SIGHTINGTIME IN CAT_SIGHTINGS.SIGHTINGTIME%TYPE,
        P_REMARK       IN CAT_SIGHTINGS.REMARK%TYPE,
        O_SIGHTINGID   OUT CAT_SIGHTINGS.SIGHTINGID%TYPE
    );

    -- 16. 创建猫咪失踪预警。
    PROCEDURE CREATE_MISSING_ALERT(
        P_CATID            IN CAT_MISSINGALERTS.CATID%TYPE,
        P_LASTSIGHTINGID   IN CAT_MISSINGALERTS.LASTSIGHTINGID%TYPE,
        P_LASTSIGHTINGTIME IN CAT_MISSINGALERTS.LASTSIGHTINGTIME%TYPE,
        P_THRESHOLDDAYS    IN CAT_MISSINGALERTS.THRESHOLDDAYS%TYPE,
        P_HANDLERUSERID    IN CAT_MISSINGALERTS.HANDLERUSERID%TYPE,
        P_REMARK           IN CAT_MISSINGALERTS.REMARK%TYPE,
        O_ALERTID          OUT CAT_MISSINGALERTS.ALERTID%TYPE
    );

    -- 16. 更新失踪预警状态。
    PROCEDURE UPDATE_MISSING_STATUS(
        P_ALERTID       IN CAT_MISSINGALERTS.ALERTID%TYPE,
        P_ALERTSTATUS   IN CAT_MISSINGALERTS.ALERTSTATUS%TYPE,
        P_HANDLERUSERID IN CAT_MISSINGALERTS.HANDLERUSERID%TYPE,
        P_REMARK        IN CAT_MISSINGALERTS.REMARK%TYPE
    );

    -- 14. 扫描健康记录，为有 NEXTDUEDATE 但还没有提醒的记录补建提醒。
    PROCEDURE AUTO_CREATE_REMINDERS_FROM_HEALTH;
END PKG_RESCUE_141516;
/

SHOW ERRORS PACKAGE PKG_RESCUE_141516
