PROMPT Creating rescue 14/15/16 package body...

CREATE OR REPLACE PACKAGE BODY PKG_RESCUE_141516 AS
    FUNCTION NEW_ID RETURN VARCHAR2 AS
    BEGIN
        RETURN LOWER(RAWTOHEX(SYS_GUID()));
    END NEW_ID;

    PROCEDURE ASSERT_NOT_BLANK(
        P_VALUE         IN VARCHAR2,
        P_ERROR_CODE    IN NUMBER,
        P_ERROR_MESSAGE IN VARCHAR2
    ) AS
    BEGIN
        IF P_VALUE IS NULL OR TRIM(P_VALUE) IS NULL THEN
            RAISE_APPLICATION_ERROR(P_ERROR_CODE, P_ERROR_MESSAGE);
        END IF;
    END ASSERT_NOT_BLANK;

    PROCEDURE ASSERT_STATUS(
        P_VALUE         IN VARCHAR2,
        P_ALLOWED       IN VARCHAR2,
        P_ERROR_CODE    IN NUMBER,
        P_ERROR_MESSAGE IN VARCHAR2
    ) AS
    BEGIN
        IF P_VALUE IS NULL OR INSTR(',' || P_ALLOWED || ',', ',' || P_VALUE || ',') = 0 THEN
            RAISE_APPLICATION_ERROR(P_ERROR_CODE, P_ERROR_MESSAGE || ': ' || NVL(P_VALUE, '<NULL>'));
        END IF;
    END ASSERT_STATUS;

    PROCEDURE CREATE_REMINDER(
        P_RECORDID       IN MED_REMINDERS.RECORDID%TYPE,
        P_CATID          IN MED_REMINDERS.CATID%TYPE,
        P_REMINDERTYPE   IN MED_REMINDERS.REMINDERTYPE%TYPE,
        P_RECEIVERUSERID IN MED_REMINDERS.RECEIVERUSERID%TYPE,
        P_REMINDERTIME   IN MED_REMINDERS.REMINDERTIME%TYPE,
        O_REMINDERID     OUT MED_REMINDERS.REMINDERID%TYPE
    ) AS
    BEGIN
        ASSERT_NOT_BLANK(P_CATID, -20120, 'Cat id is required');
        ASSERT_NOT_BLANK(P_REMINDERTYPE, -20121, 'Reminder type is required');

        IF P_REMINDERTIME IS NULL THEN
            RAISE_APPLICATION_ERROR(-20122, 'Reminder time is required');
        END IF;

        ASSERT_STATUS(
            UPPER(P_REMINDERTYPE),
            'VACCINE,DEWORM,STERILIZATION,RECHECK,OTHER',
            -20123,
            'Invalid reminder type'
        );

        O_REMINDERID := NEW_ID();

        INSERT INTO MED_REMINDERS (
            REMINDERID,
            RECORDID,
            CATID,
            REMINDERTYPE,
            RECEIVERUSERID,
            REMINDERTIME,
            SENDSTATUS
        ) VALUES (
            O_REMINDERID,
            P_RECORDID,
            P_CATID,
            UPPER(P_REMINDERTYPE),
            P_RECEIVERUSERID,
            P_REMINDERTIME,
            'PENDING'
        );
    END CREATE_REMINDER;

    PROCEDURE MARK_REMINDER_SENT(P_REMINDERID IN MED_REMINDERS.REMINDERID%TYPE) AS
    BEGIN
        ASSERT_NOT_BLANK(P_REMINDERID, -20124, 'Reminder id is required');

        UPDATE MED_REMINDERS
        SET SENDSTATUS = 'SENT'
        WHERE REMINDERID = P_REMINDERID;

        IF SQL%ROWCOUNT = 0 THEN
            RAISE_APPLICATION_ERROR(-20125, 'Reminder not found');
        END IF;
    END MARK_REMINDER_SENT;

    PROCEDURE COMPLETE_REMINDER(P_REMINDERID IN MED_REMINDERS.REMINDERID%TYPE) AS
    BEGIN
        ASSERT_NOT_BLANK(P_REMINDERID, -20126, 'Reminder id is required');

        UPDATE MED_REMINDERS
        SET SENDSTATUS = 'COMPLETED'
        WHERE REMINDERID = P_REMINDERID;

        IF SQL%ROWCOUNT = 0 THEN
            RAISE_APPLICATION_ERROR(-20127, 'Reminder not found');
        END IF;
    END COMPLETE_REMINDER;

    PROCEDURE SUBMIT_EMERGENCY_REPORT(
        P_REPORTERUSERID IN EMERGENCY_REPORTS.REPORTERUSERID%TYPE,
        P_AREAID         IN EMERGENCY_REPORTS.AREAID%TYPE,
        P_ANIMALTYPE     IN EMERGENCY_REPORTS.ANIMALTYPE%TYPE,
        P_PHOTOURL       IN EMERGENCY_REPORTS.PHOTOURL%TYPE,
        P_LONGITUDE      IN EMERGENCY_REPORTS.LONGITUDE%TYPE,
        P_LATITUDE       IN EMERGENCY_REPORTS.LATITUDE%TYPE,
        P_URGENCYLEVEL   IN EMERGENCY_REPORTS.URGENCYLEVEL%TYPE,
        O_REPORTID       OUT EMERGENCY_REPORTS.REPORTID%TYPE
    ) AS
    BEGIN
        ASSERT_NOT_BLANK(P_REPORTERUSERID, -20130, 'Reporter user id is required');
        ASSERT_NOT_BLANK(P_AREAID, -20131, 'Area id is required');
        ASSERT_NOT_BLANK(P_ANIMALTYPE, -20132, 'Animal type is required');
        ASSERT_NOT_BLANK(P_URGENCYLEVEL, -20133, 'Urgency level is required');
        ASSERT_STATUS(
            UPPER(P_URGENCYLEVEL),
            'LOW,MEDIUM,HIGH,CRITICAL',
            -20134,
            'Invalid urgency level'
        );

        O_REPORTID := NEW_ID();

        INSERT INTO EMERGENCY_REPORTS (
            REPORTID,
            REPORTERUSERID,
            AREAID,
            ANIMALTYPE,
            PHOTOURL,
            LONGITUDE,
            LATITUDE,
            REPORTTIME,
            URGENCYLEVEL,
            PROCESSSTATUS
        ) VALUES (
            O_REPORTID,
            P_REPORTERUSERID,
            P_AREAID,
            P_ANIMALTYPE,
            P_PHOTOURL,
            P_LONGITUDE,
            P_LATITUDE,
            SYSDATE,
            UPPER(P_URGENCYLEVEL),
            'SUBMITTED'
        );
    END SUBMIT_EMERGENCY_REPORT;

    PROCEDURE ASSIGN_EMERGENCY_REPORT(
        P_REPORTID      IN EMERGENCY_REPORTS.REPORTID%TYPE,
        P_HANDLERUSERID IN EMERGENCY_REPORTS.HANDLERUSERID%TYPE
    ) AS
    BEGIN
        ASSERT_NOT_BLANK(P_REPORTID, -20135, 'Emergency report id is required');
        ASSERT_NOT_BLANK(P_HANDLERUSERID, -20136, 'Handler user id is required');

        UPDATE EMERGENCY_REPORTS
        SET HANDLERUSERID = P_HANDLERUSERID,
            PROCESSSTATUS = 'ASSIGNED'
        WHERE REPORTID = P_REPORTID;

        IF SQL%ROWCOUNT = 0 THEN
            RAISE_APPLICATION_ERROR(-20137, 'Emergency report not found');
        END IF;
    END ASSIGN_EMERGENCY_REPORT;

    PROCEDURE UPDATE_EMERGENCY_STATUS(
        P_REPORTID      IN EMERGENCY_REPORTS.REPORTID%TYPE,
        P_PROCESSSTATUS IN EMERGENCY_REPORTS.PROCESSSTATUS%TYPE,
        P_PROCESSRESULT IN EMERGENCY_REPORTS.PROCESSRESULT%TYPE
    ) AS
    BEGIN
        ASSERT_NOT_BLANK(P_REPORTID, -20138, 'Emergency report id is required');
        ASSERT_NOT_BLANK(P_PROCESSSTATUS, -20139, 'Process status is required');
        ASSERT_STATUS(
            UPPER(P_PROCESSSTATUS),
            'SUBMITTED,ASSIGNED,PROCESSING,RESOLVED,CLOSED',
            -20140,
            'Invalid process status'
        );

        UPDATE EMERGENCY_REPORTS
        SET PROCESSSTATUS = UPPER(P_PROCESSSTATUS),
            PROCESSRESULT = P_PROCESSRESULT
        WHERE REPORTID = P_REPORTID;

        IF SQL%ROWCOUNT = 0 THEN
            RAISE_APPLICATION_ERROR(-20141, 'Emergency report not found');
        END IF;
    END UPDATE_EMERGENCY_STATUS;

    PROCEDURE CREATE_SIGHTING(
        P_CATID        IN CAT_SIGHTINGS.CATID%TYPE,
        P_USERID       IN CAT_SIGHTINGS.USERID%TYPE,
        P_AREAID       IN CAT_SIGHTINGS.AREAID%TYPE,
        P_LONGITUDE    IN CAT_SIGHTINGS.LONGITUDE%TYPE,
        P_LATITUDE     IN CAT_SIGHTINGS.LATITUDE%TYPE,
        P_PHOTOURL     IN CAT_SIGHTINGS.PHOTOURL%TYPE,
        P_SIGHTINGTIME IN CAT_SIGHTINGS.SIGHTINGTIME%TYPE,
        P_REMARK       IN CAT_SIGHTINGS.REMARK%TYPE,
        O_SIGHTINGID   OUT CAT_SIGHTINGS.SIGHTINGID%TYPE
    ) AS
    BEGIN
        ASSERT_NOT_BLANK(P_CATID, -20150, 'Cat id is required');
        ASSERT_NOT_BLANK(P_AREAID, -20151, 'Area id is required');

        IF P_SIGHTINGTIME IS NULL THEN
            RAISE_APPLICATION_ERROR(-20152, 'Sighting time is required');
        END IF;

        O_SIGHTINGID := NEW_ID();

        INSERT INTO CAT_SIGHTINGS (
            SIGHTINGID,
            CATID,
            USERID,
            AREAID,
            LONGITUDE,
            LATITUDE,
            PHOTOURL,
            SIGHTINGTIME,
            REMARK
        ) VALUES (
            O_SIGHTINGID,
            P_CATID,
            P_USERID,
            P_AREAID,
            P_LONGITUDE,
            P_LATITUDE,
            P_PHOTOURL,
            P_SIGHTINGTIME,
            P_REMARK
        );
    END CREATE_SIGHTING;

    PROCEDURE CREATE_MISSING_ALERT(
        P_CATID            IN CAT_MISSINGALERTS.CATID%TYPE,
        P_LASTSIGHTINGID   IN CAT_MISSINGALERTS.LASTSIGHTINGID%TYPE,
        P_LASTSIGHTINGTIME IN CAT_MISSINGALERTS.LASTSIGHTINGTIME%TYPE,
        P_THRESHOLDDAYS    IN CAT_MISSINGALERTS.THRESHOLDDAYS%TYPE,
        P_HANDLERUSERID    IN CAT_MISSINGALERTS.HANDLERUSERID%TYPE,
        P_REMARK           IN CAT_MISSINGALERTS.REMARK%TYPE,
        O_ALERTID          OUT CAT_MISSINGALERTS.ALERTID%TYPE
    ) AS
    BEGIN
        ASSERT_NOT_BLANK(P_CATID, -20160, 'Cat id is required');

        IF P_THRESHOLDDAYS IS NOT NULL AND P_THRESHOLDDAYS <= 0 THEN
            RAISE_APPLICATION_ERROR(-20161, 'Threshold days must be greater than 0');
        END IF;

        O_ALERTID := NEW_ID();

        INSERT INTO CAT_MISSINGALERTS (
            ALERTID,
            CATID,
            LASTSIGHTINGID,
            LASTSIGHTINGTIME,
            THRESHOLDDAYS,
            ALERTTIME,
            ALERTSTATUS,
            HANDLERUSERID,
            REMARK
        ) VALUES (
            O_ALERTID,
            P_CATID,
            P_LASTSIGHTINGID,
            P_LASTSIGHTINGTIME,
            P_THRESHOLDDAYS,
            SYSDATE,
            'PROCESSING',
            P_HANDLERUSERID,
            P_REMARK
        );
    END CREATE_MISSING_ALERT;

    PROCEDURE UPDATE_MISSING_STATUS(
        P_ALERTID       IN CAT_MISSINGALERTS.ALERTID%TYPE,
        P_ALERTSTATUS   IN CAT_MISSINGALERTS.ALERTSTATUS%TYPE,
        P_HANDLERUSERID IN CAT_MISSINGALERTS.HANDLERUSERID%TYPE,
        P_REMARK        IN CAT_MISSINGALERTS.REMARK%TYPE
    ) AS
    BEGIN
        ASSERT_NOT_BLANK(P_ALERTID, -20170, 'Missing alert id is required');
        ASSERT_NOT_BLANK(P_ALERTSTATUS, -20171, 'Missing alert status is required');
        ASSERT_NOT_BLANK(P_HANDLERUSERID, -20172, 'Handler user id is required');
        ASSERT_STATUS(
            UPPER(P_ALERTSTATUS),
            'PROCESSING,FOUND,CLOSED',
            -20173,
            'Invalid missing alert status'
        );

        UPDATE CAT_MISSINGALERTS
        SET ALERTSTATUS = UPPER(P_ALERTSTATUS),
            HANDLERUSERID = P_HANDLERUSERID,
            REMARK = NVL(P_REMARK, REMARK),
            CLOSETIME = CASE
                WHEN UPPER(P_ALERTSTATUS) IN ('FOUND', 'CLOSED') THEN SYSDATE
                ELSE CLOSETIME
            END
        WHERE ALERTID = P_ALERTID;

        IF SQL%ROWCOUNT = 0 THEN
            RAISE_APPLICATION_ERROR(-20174, 'Missing alert not found');
        END IF;
    END UPDATE_MISSING_STATUS;

    PROCEDURE AUTO_CREATE_REMINDERS_FROM_HEALTH AS
    BEGIN
        INSERT INTO MED_REMINDERS (
            REMINDERID,
            RECORDID,
            CATID,
            REMINDERTYPE,
            REMINDERTIME,
            SENDSTATUS
        )
        SELECT LOWER(RAWTOHEX(SYS_GUID())),
               H.RECORDID,
               H.CATID,
               CASE UPPER(H.RECORDTYPE)
                   WHEN 'VACCINE' THEN 'VACCINE'
                   WHEN 'DEWORM' THEN 'DEWORM'
                   WHEN 'STERILIZATION' THEN 'STERILIZATION'
                   ELSE 'RECHECK'
               END,
               H.NEXTDUEDATE,
               'PENDING'
        FROM MED_HEALTHRECORDS H
        WHERE H.NEXTDUEDATE IS NOT NULL
          AND NOT EXISTS (
              SELECT 1
              FROM MED_REMINDERS R
              WHERE R.RECORDID = H.RECORDID
          );
    END AUTO_CREATE_REMINDERS_FROM_HEALTH;
END PKG_RESCUE_141516;
/

SHOW ERRORS PACKAGE BODY PKG_RESCUE_141516
