PROMPT Requirement 14: reminders...

COLUMN REMINDERID FORMAT A36
COLUMN CATID FORMAT A20
COLUMN REMINDERTYPE FORMAT A16
COLUMN RECEIVERUSERID FORMAT A26
COLUMN SENDSTATUS FORMAT A12

-- 验证 Package 能根据健康记录自动补建提醒。
BEGIN
    PKG_RESCUE_141516.AUTO_CREATE_REMINDERS_FROM_HEALTH;
    COMMIT;
END;
/

-- 验证 C# 调用路径：CREATE_REMINDER -> MARK_REMINDER_SENT -> COMPLETE_REMINDER。
DECLARE
    V_REMINDERID MED_REMINDERS.REMINDERID%TYPE;
BEGIN
    PKG_RESCUE_141516.CREATE_REMINDER(
        P_RECORDID       => NULL,
        P_CATID          => 'cat-demo-141516',
        P_REMINDERTYPE   => 'DEWORM',
        P_RECEIVERUSERID => 'user-demo-handler-141516',
        P_REMINDERTIME   => SYSDATE + 60,
        O_REMINDERID     => V_REMINDERID
    );

    DBMS_OUTPUT.PUT_LINE('Manual reminder: ' || V_REMINDERID);

    PKG_RESCUE_141516.MARK_REMINDER_SENT(V_REMINDERID);
    PKG_RESCUE_141516.COMPLETE_REMINDER(V_REMINDERID);
    COMMIT;
END;
/

-- 验证 Repository 查询使用的视图可读。
SELECT REMINDERID,
       CATID,
       REMINDERTYPE,
       RECEIVERUSERID,
       REMINDERTIME,
       SENDSTATUS
FROM V_MED_REMINDERS
WHERE CATID = 'cat-demo-141516'
ORDER BY REMINDERTIME DESC;

SELECT REMINDERID,
       CATID,
       REMINDERTYPE,
       REMINDERTIME,
       SENDSTATUS
FROM V_MED_PENDING_REMINDERS
WHERE CATID = 'cat-demo-141516'
ORDER BY REMINDERTIME DESC;
