PROMPT Requirement 15: emergency reports...

COLUMN REPORTID FORMAT A36
COLUMN REPORTERUSERID FORMAT A26
COLUMN AREAID FORMAT A20
COLUMN ANIMALTYPE FORMAT A12
COLUMN URGENCYLEVEL FORMAT A12
COLUMN PROCESSSTATUS FORMAT A14
COLUMN HANDLERUSERID FORMAT A26
COLUMN PROCESSRESULT FORMAT A45

-- 验证 C# 调用路径：提交上报 -> 分配处理人 -> 更新处理状态。
DECLARE
    V_REPORTID EMERGENCY_REPORTS.REPORTID%TYPE;
BEGIN
    PKG_RESCUE_141516.SUBMIT_EMERGENCY_REPORT(
        P_REPORTERUSERID => 'user-demo-reporter-141516',
        P_AREAID         => 'area-demo-141516',
        P_ANIMALTYPE     => 'CAT',
        P_PHOTOURL       => 'https://example.com/emergency-cat.jpg',
        P_LONGITUDE      => 121.215,
        P_LATITUDE       => 31.289,
        P_URGENCYLEVEL   => 'HIGH',
        O_REPORTID       => V_REPORTID
    );

    DBMS_OUTPUT.PUT_LINE('Created emergency report: ' || V_REPORTID);

    PKG_RESCUE_141516.ASSIGN_EMERGENCY_REPORT(V_REPORTID, 'user-demo-handler-141516');
    PKG_RESCUE_141516.UPDATE_EMERGENCY_STATUS(
        V_REPORTID,
        'RESOLVED',
        'Volunteer arrived and sent the cat to the clinic.'
    );
    COMMIT;
END;
/

-- 验证 Repository 查询使用的视图可读。
SELECT REPORTID,
       REPORTERUSERID,
       AREAID,
       ANIMALTYPE,
       URGENCYLEVEL,
       PROCESSSTATUS,
       HANDLERUSERID,
       PROCESSRESULT
FROM V_EMERGENCY_REPORTS
WHERE REPORTERUSERID = 'user-demo-reporter-141516'
ORDER BY REPORTTIME DESC;
