SET DEFINE OFF;
SET SERVEROUTPUT ON;

PROMPT ===== Removing fixed acceptance seed data =====;
-- 仅删除 ID 以 seed- 开头的数据，按外键依赖反向执行。

DELETE FROM CAT_MATCHRECORDS WHERE MATCHID LIKE 'seed-%';
DELETE FROM VOTE_NAMINGRECORDS WHERE RECORDID LIKE 'seed-%';
DELETE FROM VOTE_NAMINGCANDIDATES WHERE CANDIDATEID LIKE 'seed-%';
DELETE FROM CAT_MISSINGALERTS WHERE ALERTID LIKE 'seed-%';
DELETE FROM ADOPT_VISITS WHERE VISITID LIKE 'seed-%';
DELETE FROM USER_BLACKLIST WHERE BLACKLISTID LIKE 'seed-%';
DELETE FROM ADOPT_APPLICATIONS WHERE APPLICATIONID LIKE 'seed-%';
DELETE FROM VOL_HANDOVERS WHERE HANDOVERID LIKE 'seed-%';
DELETE FROM VOL_CHECKINS WHERE CHECKINID LIKE 'seed-%';
DELETE FROM VOL_CREDITLOGS WHERE CREDITLOGID LIKE 'seed-%';
DELETE FROM VOL_SHIFTS WHERE SHIFTID LIKE 'seed-%';
DELETE FROM VOL_VOLUNTEERS WHERE VOLUNTEERID LIKE 'seed-%';
-- Health-record inserts may create reminder rows with generated IDs, so match
-- both the reminder ID and its seed parent.
DELETE FROM MED_REMINDERS
WHERE REMINDERID LIKE 'seed-%' OR RECORDID LIKE 'seed-%' OR CATID LIKE 'seed-%';
DELETE FROM MED_HEALTHRECORDS WHERE RECORDID LIKE 'seed-%';
DELETE FROM TNR_STATUSLOGS WHERE LOGID LIKE 'seed-%';
DELETE FROM TNR_CASES WHERE CASEID LIKE 'seed-%';
DELETE FROM FUND_DONATIONS WHERE DONATIONID LIKE 'seed-%';
DELETE FROM FUND_FINANCERECORDS WHERE FINANCEID LIKE 'seed-%';
DELETE FROM RPT_STATISTICSSNAPSHOTS WHERE SNAPSHOTID LIKE 'seed-%';
DELETE FROM FUND_CROWDFUNDINGPROJECTS WHERE PROJECTID LIKE 'seed-%';
DELETE FROM NEST_MAINTENANCERECORDS WHERE MAINTENANCEID LIKE 'seed-%';
DELETE FROM EMERGENCY_REPORTS WHERE REPORTID LIKE 'seed-%';
DELETE FROM CAT_SIGHTINGS WHERE SIGHTINGID LIKE 'seed-%';
DELETE FROM CAT_PHOTOS WHERE PHOTOID LIKE 'seed-%';
DELETE FROM CAT_CATS WHERE CATID LIKE 'seed-%';
DELETE FROM MAP_SERVICEPOINTS WHERE POINTID LIKE 'seed-%';
DELETE FROM MAP_CAMPUSAREAS WHERE AREAID LIKE 'seed-%';
DELETE FROM SYS_USERS WHERE USERID LIKE 'seed-%';
DELETE FROM SYS_ROLES WHERE ROLEID LIKE 'seed-%';

COMMIT;
PROMPT ===== Fixed acceptance seed data removed =====;
