SET DEFINE OFF;
PROMPT ===== Creating tables =====;

PROMPT Creating SYS_ROLES...;
CREATE TABLE SYS_ROLES (
    ROLEID VARCHAR2(36) PRIMARY KEY,
    ROLENAME VARCHAR2(50) NOT NULL,
    DESCRIPTION VARCHAR2(200),
    PERMISSIONSCOPE VARCHAR2(500)
);

PROMPT Creating SYS_USERS...;
CREATE TABLE SYS_USERS (
    USERID VARCHAR2(36) PRIMARY KEY,
    ROLEID VARCHAR2(36) NOT NULL REFERENCES SYS_ROLES(ROLEID),
    USERNAME VARCHAR2(50) NOT NULL UNIQUE,
    PASSWORDHASH VARCHAR2(255) NOT NULL,
    REALNAME VARCHAR2(50),
    STUDENTNO VARCHAR2(30),
    PHONE VARCHAR2(20),
    VERIFYSTATUS VARCHAR2(20),
    STATUS VARCHAR2(20)
);

PROMPT Creating MAP_CAMPUSAREAS...;
CREATE TABLE MAP_CAMPUSAREAS (
    AREAID VARCHAR2(36) PRIMARY KEY,
    AREANAME VARCHAR2(100) NOT NULL,
    CAMPUSNAME VARCHAR2(100),
    PARENTAREAID VARCHAR2(36),
    AREATYPE VARCHAR2(30),
    RISKLEVEL VARCHAR2(20),
    GEOBOUNDARY CLOB
);

PROMPT Creating CAT_CATS...;
CREATE TABLE CAT_CATS (
    CATID VARCHAR2(36) PRIMARY KEY,
    CATNAME VARCHAR2(50),
    GENDER VARCHAR2(10),
    BREED VARCHAR2(50),
    COLORPATTERN VARCHAR2(100),
    STERILIZEDFLAG NUMBER(1) DEFAULT 0,
    EARTIPFLAG NUMBER(1) DEFAULT 0,
    PERSONALITYTAGS VARCHAR2(200),
    MAINAREAID VARCHAR2(36) REFERENCES MAP_CAMPUSAREAS(AREAID),
    LIFESTATUS VARCHAR2(20),
    ARCHIVESTATUS VARCHAR2(20)
);

PROMPT Creating CAT_PHOTOS...;
CREATE TABLE CAT_PHOTOS (
    PHOTOID VARCHAR2(36) PRIMARY KEY,
    CATID VARCHAR2(36) REFERENCES CAT_CATS(CATID),
    PHOTOURL VARCHAR2(300) NOT NULL,
    FEATUREVECTOR CLOB,
    UPLOADUSERID VARCHAR2(36) REFERENCES SYS_USERS(USERID),
    UPLOADTIME DATE,
    ISPRIMARY NUMBER(1) DEFAULT 0
);

PROMPT Creating unique primary photo index...;
CREATE UNIQUE INDEX UQ_CAT_PHOTOS_PRIMARY
ON CAT_PHOTOS (CASE WHEN ISPRIMARY = 1 THEN CATID END);

PROMPT Creating MAP_SERVICEPOINTS...;
CREATE TABLE MAP_SERVICEPOINTS (
    POINTID VARCHAR2(36) PRIMARY KEY,
    AREAID VARCHAR2(36) REFERENCES MAP_CAMPUSAREAS(AREAID),
    POINTNAME VARCHAR2(100) NOT NULL,
    POINTTYPE VARCHAR2(30),
    LONGITUDE NUMBER(12,8),
    LATITUDE NUMBER(12,8),
    FACILITYSTATUS VARCHAR2(20),
    DEPLOYTIME DATE
);

PROMPT Creating CAT_SIGHTINGS...;
CREATE TABLE CAT_SIGHTINGS (
    SIGHTINGID VARCHAR2(36) PRIMARY KEY,
    CATID VARCHAR2(36) REFERENCES CAT_CATS(CATID),
    USERID VARCHAR2(36) REFERENCES SYS_USERS(USERID),
    AREAID VARCHAR2(36) REFERENCES MAP_CAMPUSAREAS(AREAID),
    LONGITUDE NUMBER(12,8),
    LATITUDE NUMBER(12,8),
    PHOTOURL VARCHAR2(300),
    SIGHTINGTIME DATE,
    REMARK VARCHAR2(300)
);

PROMPT Creating CAT_MATCHRECORDS...;
CREATE TABLE CAT_MATCHRECORDS (
    MATCHID VARCHAR2(36) PRIMARY KEY,
    SOURCEPHOTOID VARCHAR2(36) REFERENCES CAT_PHOTOS(PHOTOID),
    CANDIDATECATID VARCHAR2(36) REFERENCES CAT_CATS(CATID),
    SIMILARITYSCORE NUMBER(5,2),
    RANKNO NUMBER(3),
    CONFIRMSTATUS VARCHAR2(20),
    CONFIRMUSERID VARCHAR2(36) REFERENCES SYS_USERS(USERID)
);

PROMPT Creating TNR_CASES...;
CREATE TABLE TNR_CASES (
    CASEID VARCHAR2(36) PRIMARY KEY,
    CATID VARCHAR2(36) REFERENCES CAT_CATS(CATID),
    RESPONSIBLEUSERID VARCHAR2(36) REFERENCES SYS_USERS(USERID),
    CURRENTSTATUS VARCHAR2(30),
    HOSPITALNAME VARCHAR2(100),
    CAPTURETIME DATE,
    SURGERYTIME DATE,
    RELEASETIME DATE,
    TOTALCOST NUMBER(10,2)
);

PROMPT Creating TNR_STATUSLOGS...;
CREATE TABLE TNR_STATUSLOGS (
    LOGID VARCHAR2(36) PRIMARY KEY,
    CASEID VARCHAR2(36) REFERENCES TNR_CASES(CASEID),
    FROMSTATUS VARCHAR2(30),
    TOSTATUS VARCHAR2(30),
    OPERATORID VARCHAR2(36) REFERENCES SYS_USERS(USERID),
    OPTIME DATE,
    REMARK VARCHAR2(300)
);

PROMPT Creating MED_HEALTHRECORDS...;
CREATE TABLE MED_HEALTHRECORDS (
    RECORDID VARCHAR2(36) PRIMARY KEY,
    CATID VARCHAR2(36) REFERENCES CAT_CATS(CATID),
    RECORDTYPE VARCHAR2(30),
    HOSPITALNAME VARCHAR2(100),
    DIAGNOSIS VARCHAR2(500),
    RECORDDATE DATE,
    NEXTDUEDATE DATE,
    ATTACHMENTURL VARCHAR2(300)
);

PROMPT Creating MED_REMINDERS...;
CREATE TABLE MED_REMINDERS (
    REMINDERID VARCHAR2(36) PRIMARY KEY,
    RECORDID VARCHAR2(36) REFERENCES MED_HEALTHRECORDS(RECORDID),
    CATID VARCHAR2(36) REFERENCES CAT_CATS(CATID),
    REMINDERTYPE VARCHAR2(30),
    RECEIVERUSERID VARCHAR2(36) REFERENCES SYS_USERS(USERID),
    REMINDERTIME DATE,
    SENDSTATUS VARCHAR2(20)
);

PROMPT Creating ADOPT_APPLICATIONS...;
CREATE TABLE ADOPT_APPLICATIONS (
    APPLICATIONID VARCHAR2(36) PRIMARY KEY,
    CATID VARCHAR2(36) REFERENCES CAT_CATS(CATID),
    APPLICANTUSERID VARCHAR2(36) REFERENCES SYS_USERS(USERID),
    APPLYTIME DATE,
    CURRENTSTATUS VARCHAR2(30),
    REVIEWERUSERID VARCHAR2(36) REFERENCES SYS_USERS(USERID),
    AGREEMENTNO VARCHAR2(100),
    CONFIRMTIME DATE
);

PROMPT Creating ADOPT_VISITS...;
CREATE TABLE ADOPT_VISITS (
    VISITID VARCHAR2(36) PRIMARY KEY,
    APPLICATIONID VARCHAR2(36) REFERENCES ADOPT_APPLICATIONS(APPLICATIONID),
    VISITTYPE VARCHAR2(30),
    VISITTIME DATE,
    VISITORUSERID VARCHAR2(36) REFERENCES SYS_USERS(USERID),
    CONCLUSION VARCHAR2(500),
    PASSFLAG NUMBER(1) DEFAULT 0
);

PROMPT Creating VOL_VOLUNTEERS...;
CREATE TABLE VOL_VOLUNTEERS (
    VOLUNTEERID VARCHAR2(36) PRIMARY KEY,
    USERID VARCHAR2(36) REFERENCES SYS_USERS(USERID),
    JOINDATE DATE,
    SERVICESCORE NUMBER(10) DEFAULT 0,
    CREDITLEVEL VARCHAR2(20),
    ACTIVESTATUS VARCHAR2(20),
    GRADUATIONYEAR VARCHAR2(10)
);

PROMPT Creating VOL_SHIFTS...;
CREATE TABLE VOL_SHIFTS (
    SHIFTID VARCHAR2(36) PRIMARY KEY,
    VOLUNTEERID VARCHAR2(36) REFERENCES VOL_VOLUNTEERS(VOLUNTEERID),
    POINTID VARCHAR2(36) REFERENCES MAP_SERVICEPOINTS(POINTID),
    BACKUPVOLUNTEERID VARCHAR2(36) REFERENCES VOL_VOLUNTEERS(VOLUNTEERID),
    PLANSTARTTIME DATE,
    PLANENDTIME DATE,
    SHIFTSTATUS VARCHAR2(20)
);

PROMPT Creating VOL_CHECKINS...;
CREATE TABLE VOL_CHECKINS (
    CHECKINID VARCHAR2(36) PRIMARY KEY,
    SHIFTID VARCHAR2(36) REFERENCES VOL_SHIFTS(SHIFTID),
    CHECKINTIME DATE,
    LONGITUDE NUMBER(12,8),
    LATITUDE NUMBER(12,8),
    PHOTOURL VARCHAR2(300),
    DISTANCEMETERS NUMBER(10,2),
    CHECKINSTATUS VARCHAR2(20)
);

PROMPT Creating FOSTER_FOSTERNEEDS...;
CREATE TABLE FOSTER_FOSTERNEEDS (
    NEEDID VARCHAR2(36) PRIMARY KEY,
    CATID VARCHAR2(36) REFERENCES CAT_CATS(CATID),
    PUBLISHERUSERID VARCHAR2(36) REFERENCES SYS_USERS(USERID),
    FOSTERUSERID VARCHAR2(36) REFERENCES SYS_USERS(USERID),
    STARTDATE DATE,
    ENDDATE DATE,
    NEEDSTATUS VARCHAR2(20)
);

PROMPT Creating FOSTER_DAILYREPORTS...;
CREATE TABLE FOSTER_DAILYREPORTS (
    REPORTID VARCHAR2(36) PRIMARY KEY,
    NEEDID VARCHAR2(36) REFERENCES FOSTER_FOSTERNEEDS(NEEDID),
    REPORTDATE DATE,
    PHOTOURL VARCHAR2(300),
    DIETRECORD VARCHAR2(300),
    HEALTHSTATUS VARCHAR2(200),
    ALERTFLAG NUMBER(1) DEFAULT 0
);

PROMPT Creating VOTE_NAMINGCANDIDATES...;
CREATE TABLE VOTE_NAMINGCANDIDATES (
    CANDIDATEID VARCHAR2(36) PRIMARY KEY,
    CATID VARCHAR2(36) REFERENCES CAT_CATS(CATID),
    CANDIDATENAME VARCHAR2(50) NOT NULL,
    PROPOSERUSERID VARCHAR2(36) REFERENCES SYS_USERS(USERID),
    VOTECOUNT NUMBER(10) DEFAULT 0,
    DEADLINE DATE,
    WINFLAG NUMBER(1) DEFAULT 0
);

PROMPT Creating CAT_RELATIONSHIPS...;
CREATE TABLE CAT_RELATIONSHIPS (
    RELATIONID VARCHAR2(36) PRIMARY KEY,
    SOURCECATID VARCHAR2(36) REFERENCES CAT_CATS(CATID),
    TARGETCATID VARCHAR2(36) REFERENCES CAT_CATS(CATID),
    RELATIONTYPE VARCHAR2(30),
    EVIDENCESOURCE VARCHAR2(200),
    CONFIDENCESCORE NUMBER(5,2),
    UPDATETIME DATE
);

PROMPT Creating FUND_CROWDFUNDINGPROJECTS...;
CREATE TABLE FUND_CROWDFUNDINGPROJECTS (
    PROJECTID VARCHAR2(36) PRIMARY KEY,
    CATID VARCHAR2(36) REFERENCES CAT_CATS(CATID),
    TITLE VARCHAR2(100) NOT NULL,
    TARGETAMOUNT NUMBER(10,2),
    RAISEDAMOUNT NUMBER(10,2) DEFAULT 0,
    STARTTIME DATE,
    ENDTIME DATE,
    PROJECTSTATUS VARCHAR2(20)
);

PROMPT Creating FUND_DONATIONS...;
CREATE TABLE FUND_DONATIONS (
    DONATIONID VARCHAR2(36) PRIMARY KEY,
    PROJECTID VARCHAR2(36) REFERENCES FUND_CROWDFUNDINGPROJECTS(PROJECTID),
    DONORUSERID VARCHAR2(36) REFERENCES SYS_USERS(USERID),
    AMOUNT NUMBER(10,2),
    PAYMETHOD VARCHAR2(30),
    PAYTIME DATE,
    PUBLICFLAG NUMBER(1) DEFAULT 0
);

PROMPT Creating FUND_FINANCERECORDS...;
CREATE TABLE FUND_FINANCERECORDS (
    FINANCEID VARCHAR2(36) PRIMARY KEY,
    PROJECTID VARCHAR2(36) REFERENCES FUND_CROWDFUNDINGPROJECTS(PROJECTID),
    RECORDTYPE VARCHAR2(20),
    AMOUNT NUMBER(10,2),
    INVOICEURL VARCHAR2(300),
    AUDITUSERID VARCHAR2(36) REFERENCES SYS_USERS(USERID),
    AUDITSTATUS VARCHAR2(20),
    PUBLICTIME DATE
);

PROMPT Creating CMS_NOTICES...;
CREATE TABLE CMS_NOTICES (
    NOTICEID VARCHAR2(36) PRIMARY KEY,
    TITLE VARCHAR2(100) NOT NULL,
    NOTICETYPE VARCHAR2(30),
    CONTENT CLOB,
    PUBLISHERUSERID VARCHAR2(36) REFERENCES SYS_USERS(USERID),
    TOPFLAG NUMBER(1) DEFAULT 0,
    PUBLISHTIME DATE,
    STATUS VARCHAR2(20)
);

PROMPT Creating LOG_AUDITTRAILS...;
CREATE TABLE LOG_AUDITTRAILS (
    LOGID VARCHAR2(36) PRIMARY KEY,
    TABLENAME VARCHAR2(50),
    RECORDID VARCHAR2(36),
    ACTIONTYPE VARCHAR2(20),
    OLDVALUE CLOB,
    NEWVALUE CLOB,
    OPERATORID VARCHAR2(36) REFERENCES SYS_USERS(USERID),
    OPTIME DATE,
    CLIENTIP VARCHAR2(50)
);

PROMPT Creating VOTE_NAMINGRECORDS...;
CREATE TABLE VOTE_NAMINGRECORDS (
    RECORDID VARCHAR2(36) PRIMARY KEY,
    CANDIDATEID VARCHAR2(36) REFERENCES VOTE_NAMINGCANDIDATES(CANDIDATEID),
    VOTERUSERID VARCHAR2(36) REFERENCES SYS_USERS(USERID),
    VOTETIME DATE NOT NULL,
    CLIENTIP VARCHAR2(50),
    VOTESTATUS VARCHAR2(20),
    UNIQUE (CANDIDATEID, VOTERUSERID)
);

PROMPT Creating CAT_MISSINGALERTS...;
CREATE TABLE CAT_MISSINGALERTS (
    ALERTID VARCHAR2(36) PRIMARY KEY,
    CATID VARCHAR2(36) REFERENCES CAT_CATS(CATID),
    LASTSIGHTINGID VARCHAR2(36) REFERENCES CAT_SIGHTINGS(SIGHTINGID),
    LASTSIGHTINGTIME DATE,
    THRESHOLDDAYS NUMBER(3),
    ALERTTIME DATE NOT NULL,
    ALERTSTATUS VARCHAR2(20),
    HANDLERUSERID VARCHAR2(36) REFERENCES SYS_USERS(USERID),
    CLOSETIME DATE,
    REMARK VARCHAR2(300)
);

PROMPT Creating NEST_MAINTENANCERECORDS...;
CREATE TABLE NEST_MAINTENANCERECORDS (
    MAINTENANCEID VARCHAR2(36) PRIMARY KEY,
    POINTID VARCHAR2(36) REFERENCES MAP_SERVICEPOINTS(POINTID),
    MATERIALTYPE VARCHAR2(50),
    CHECKTIME DATE,
    WEATHERCONDITION VARCHAR2(100),
    DAMAGELEVEL VARCHAR2(20),
    ACTIONTYPE VARCHAR2(30),
    OPERATORUSERID VARCHAR2(36) REFERENCES SYS_USERS(USERID),
    NEXTCHECKTIME DATE,
    REMARK VARCHAR2(300)
);

PROMPT Creating EMERGENCY_REPORTS...;
CREATE TABLE EMERGENCY_REPORTS (
    REPORTID VARCHAR2(36) PRIMARY KEY,
    REPORTERUSERID VARCHAR2(36) REFERENCES SYS_USERS(USERID),
    AREAID VARCHAR2(36) REFERENCES MAP_CAMPUSAREAS(AREAID),
    ANIMALTYPE VARCHAR2(50),
    PHOTOURL VARCHAR2(300),
    LONGITUDE NUMBER(12,8),
    LATITUDE NUMBER(12,8),
    REPORTTIME DATE NOT NULL,
    URGENCYLEVEL VARCHAR2(20),
    PROCESSSTATUS VARCHAR2(20),
    HANDLERUSERID VARCHAR2(36) REFERENCES SYS_USERS(USERID),
    PROCESSRESULT VARCHAR2(500)
);

PROMPT Creating VOL_CREDITLOGS...;
CREATE TABLE VOL_CREDITLOGS (
    CREDITLOGID VARCHAR2(36) PRIMARY KEY,
    VOLUNTEERID VARCHAR2(36) REFERENCES VOL_VOLUNTEERS(VOLUNTEERID),
    SOURCETYPE VARCHAR2(30),
    SOURCEID VARCHAR2(36),
    SCORECHANGE NUMBER(6,2),
    CREDITLEVELAFTER VARCHAR2(20),
    CREATETIME DATE NOT NULL,
    REMARK VARCHAR2(300)
);

PROMPT Creating VOL_HANDOVERS...;
CREATE TABLE VOL_HANDOVERS (
    HANDOVERID VARCHAR2(36) PRIMARY KEY,
    FROMVOLUNTEERID VARCHAR2(36) REFERENCES VOL_VOLUNTEERS(VOLUNTEERID),
    TOVOLUNTEERID VARCHAR2(36) REFERENCES VOL_VOLUNTEERS(VOLUNTEERID),
    HANDOVERTYPE VARCHAR2(30),
    RELATEDTYPE VARCHAR2(30),
    RELATEDID VARCHAR2(36),
    APPLYTIME DATE,
    CONFIRMTIME DATE,
    HANDOVERSTATUS VARCHAR2(20),
    REMARK VARCHAR2(300)
);

PROMPT Creating CMS_ARTICLES...;
CREATE TABLE CMS_ARTICLES (
    ARTICLEID VARCHAR2(36) PRIMARY KEY,
    TITLE VARCHAR2(100) NOT NULL,
    CATEGORY VARCHAR2(30),
    CONTENT CLOB NOT NULL,
    AUTHORUSERID VARCHAR2(36) REFERENCES SYS_USERS(USERID),
    REVIEWUSERID VARCHAR2(36) REFERENCES SYS_USERS(USERID),
    REVIEWSTATUS VARCHAR2(20),
    TOPFLAG NUMBER(1) DEFAULT 0,
    PUBLISHTIME DATE,
    UPDATETIME DATE
);

PROMPT Creating USER_BLACKLIST...;
CREATE TABLE USER_BLACKLIST (
    BLACKLISTID VARCHAR2(36) PRIMARY KEY,
    USERID VARCHAR2(36) REFERENCES SYS_USERS(USERID),
    REASONTYPE VARCHAR2(30),
    REASONDETAIL VARCHAR2(500),
    RELATEDAPPLICATIONID VARCHAR2(36) REFERENCES ADOPT_APPLICATIONS(APPLICATIONID),
    CREATEUSERID VARCHAR2(36) REFERENCES SYS_USERS(USERID),
    CREATETIME DATE NOT NULL,
    BLACKLISTSTATUS VARCHAR2(20),
    RELEASETIME DATE
);

PROMPT Creating RPT_STATISTICSSNAPSHOTS...;
CREATE TABLE RPT_STATISTICSSNAPSHOTS (
    SNAPSHOTID VARCHAR2(36) PRIMARY KEY,
    SNAPSHOTDATE DATE NOT NULL,
    METRICCODE VARCHAR2(50),
    DIMENSIONTYPE VARCHAR2(50),
    DIMENSIONVALUE VARCHAR2(100),
    METRICVALUE NUMBER(12,4),
    UNIT VARCHAR2(20),
    GENERATETIME DATE NOT NULL,
    REMARK VARCHAR2(300)
);

PROMPT ===== Table creation complete =====;
