SET DEFINE OFF;
SET SERVEROUTPUT ON;

PROMPT ===== Rescue 14/15/16 Oracle programming layer =====;

/*
  This script is designed to run AFTER create_tables.sql.

  Covered requirements:
  14. MED_REMINDERS: create reminders, list pending reminders, mark sent/completed.
  15. EMERGENCY_REPORTS: submit emergency reports, assign handlers, update status/result.
  16. CAT_MISSINGALERTS: create missing alerts, record last sighting, update processing/found/closed status.

  Note:
  The existing EMERGENCY_REPORTS table has no DESCRIPTION or LOCATION_DESC column.
  It can store area, animal type, photo, longitude, latitude, urgency level, status,
  handler, and process result. If the teacher requires a detailed report description,
  add a DESCRIPTION VARCHAR2(500) column or store brief details in PROCESSRESULT after handling.
*/

-- 这一段先给常用查询字段建索引，方便后面按状态、猫咪、处理人查数据。
PROMPT Creating indexes...;

-- IDX_MED_REMINDERS_STATUS_TIME：按提醒状态和提醒时间查询待处理提醒，适合提醒列表和催办场景。
BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_MED_REMINDERS_STATUS_TIME ON MED_REMINDERS(SENDSTATUS, REMINDERTIME)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

-- IDX_MED_REMINDERS_CAT：按猫咪查询它的全部提醒，适合猫咪详情页查看护理历史。
BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_MED_REMINDERS_CAT ON MED_REMINDERS(CATID)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

-- IDX_EMERGENCY_STATUS_LEVEL：按处理状态和紧急等级查上报，适合管理员筛选高优先级任务。
BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_EMERGENCY_STATUS_LEVEL ON EMERGENCY_REPORTS(PROCESSSTATUS, URGENCYLEVEL)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

-- IDX_EMERGENCY_HANDLER：按处理人查询自己负责的紧急上报，适合志愿者/管理员工作台。
BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_EMERGENCY_HANDLER ON EMERGENCY_REPORTS(HANDLERUSERID)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

-- IDX_MISSING_STATUS：按失踪预警状态查询处理中、已寻回、已关闭的记录。
BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_MISSING_STATUS ON CAT_MISSINGALERTS(ALERTSTATUS)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

-- IDX_MISSING_CAT_STATUS：按猫咪和状态联合查询失踪预警，便于追踪某只猫的预警流转。
BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX IDX_MISSING_CAT_STATUS ON CAT_MISSINGALERTS(CATID, ALERTSTATUS)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

-- 这一段创建视图，把常用查询拼成更适合页面展示和验收查看的结果集。
PROMPT Creating views...;

-- V_MED_PENDING_REMINDERS：汇总提醒、猫咪、接收人和医疗记录信息，用于查看待处理/已发送提醒。
CREATE OR REPLACE VIEW V_MED_PENDING_REMINDERS AS
SELECT
    R.REMINDERID,
    R.RECORDID,
    R.CATID,
    C.CATNAME,
    R.REMINDERTYPE,
    R.RECEIVERUSERID,
    U.USERNAME AS RECEIVERUSERNAME,
    R.REMINDERTIME,
    R.SENDSTATUS,
    H.RECORDTYPE,
    H.HOSPITALNAME,
    H.DIAGNOSIS,
    H.RECORDDATE,
    H.NEXTDUEDATE
FROM MED_REMINDERS R
LEFT JOIN CAT_CATS C
    ON R.CATID = C.CATID
LEFT JOIN SYS_USERS U
    ON R.RECEIVERUSERID = U.USERID
LEFT JOIN MED_HEALTHRECORDS H
    ON R.RECORDID = H.RECORDID
WHERE NVL(R.SENDSTATUS, 'PENDING') IN ('PENDING', 'SENT');

-- V_EMERGENCY_REPORTS：汇总紧急上报、上报人、处理人和区域信息，用于管理员分配和处理上报。
CREATE OR REPLACE VIEW V_EMERGENCY_REPORTS AS
SELECT
    E.REPORTID,
    E.REPORTERUSERID,
    REPORTER.USERNAME AS REPORTERUSERNAME,
    E.AREAID,
    A.AREANAME,
    E.ANIMALTYPE,
    E.PHOTOURL,
    E.LONGITUDE,
    E.LATITUDE,
    E.REPORTTIME,
    E.URGENCYLEVEL,
    E.PROCESSSTATUS,
    E.HANDLERUSERID,
    HANDLER.USERNAME AS HANDLERUSERNAME,
    E.PROCESSRESULT
FROM EMERGENCY_REPORTS E
LEFT JOIN SYS_USERS REPORTER
    ON E.REPORTERUSERID = REPORTER.USERID
LEFT JOIN SYS_USERS HANDLER
    ON E.HANDLERUSERID = HANDLER.USERID
LEFT JOIN MAP_CAMPUSAREAS A
    ON E.AREAID = A.AREAID;

-- V_MISSING_ALERTS：汇总失踪预警、猫咪、最后目击记录、处理人和关闭信息，用于追踪寻回流程。
CREATE OR REPLACE VIEW V_MISSING_ALERTS AS
SELECT
    M.ALERTID,
    M.CATID,
    C.CATNAME,
    M.LASTSIGHTINGID,
    M.LASTSIGHTINGTIME,
    S.AREAID AS LASTSIGHTINGAREAID,
    A.AREANAME AS LASTSIGHTINGAREANAME,
    S.LONGITUDE AS LASTSIGHTINGLONGITUDE,
    S.LATITUDE AS LASTSIGHTINGLATITUDE,
    S.PHOTOURL AS LASTSIGHTINGPHOTOURL,
    S.REMARK AS LASTSIGHTINGREMARK,
    M.THRESHOLDDAYS,
    M.ALERTTIME,
    M.ALERTSTATUS,
    M.HANDLERUSERID,
    U.USERNAME AS HANDLERUSERNAME,
    M.CLOSETIME,
    M.REMARK
FROM CAT_MISSINGALERTS M
LEFT JOIN CAT_CATS C
    ON M.CATID = C.CATID
LEFT JOIN CAT_SIGHTINGS S
    ON M.LASTSIGHTINGID = S.SIGHTINGID
LEFT JOIN MAP_CAMPUSAREAS A
    ON S.AREAID = A.AREAID
LEFT JOIN SYS_USERS U
    ON M.HANDLERUSERID = U.USERID;

-- 这一段创建触发器，负责自动补主键、统一状态格式，以及医疗记录自动生成提醒。
PROMPT Creating triggers...;

-- TRG_MED_REMINDERS_BI：插入提醒时自动生成主键，并把提醒状态统一成大写，避免状态值不一致。
CREATE OR REPLACE TRIGGER TRG_MED_REMINDERS_BI
BEFORE INSERT ON MED_REMINDERS
FOR EACH ROW
BEGIN
    IF :NEW.REMINDERID IS NULL THEN
        :NEW.REMINDERID := LOWER(RAWTOHEX(SYS_GUID()));
    END IF;

    :NEW.SENDSTATUS := UPPER(NVL(:NEW.SENDSTATUS, 'PENDING'));
END;
/

-- TRG_MED_REMINDERS_BU：更新提醒时继续把状态统一成大写，防止手工修改写出不同格式。
CREATE OR REPLACE TRIGGER TRG_MED_REMINDERS_BU
BEFORE UPDATE ON MED_REMINDERS
FOR EACH ROW
BEGIN
    IF :NEW.SENDSTATUS IS NOT NULL THEN
        :NEW.SENDSTATUS := UPPER(:NEW.SENDSTATUS);
    END IF;
END;
/

-- TRG_EMERGENCY_REPORTS_BI：插入紧急上报时自动生成主键、默认上报时间和默认处理状态。
CREATE OR REPLACE TRIGGER TRG_EMERGENCY_REPORTS_BI
BEFORE INSERT ON EMERGENCY_REPORTS
FOR EACH ROW
BEGIN
    IF :NEW.REPORTID IS NULL THEN
        :NEW.REPORTID := LOWER(RAWTOHEX(SYS_GUID()));
    END IF;

    :NEW.REPORTTIME := NVL(:NEW.REPORTTIME, SYSDATE);
    :NEW.PROCESSSTATUS := UPPER(NVL(:NEW.PROCESSSTATUS, 'SUBMITTED'));

    IF :NEW.URGENCYLEVEL IS NOT NULL THEN
        :NEW.URGENCYLEVEL := UPPER(:NEW.URGENCYLEVEL);
    END IF;
END;
/

-- TRG_EMERGENCY_REPORTS_BU：更新紧急上报时统一状态和紧急等级格式，保证查询条件稳定。
CREATE OR REPLACE TRIGGER TRG_EMERGENCY_REPORTS_BU
BEFORE UPDATE ON EMERGENCY_REPORTS
FOR EACH ROW
BEGIN
    IF :NEW.PROCESSSTATUS IS NOT NULL THEN
        :NEW.PROCESSSTATUS := UPPER(:NEW.PROCESSSTATUS);
    END IF;

    IF :NEW.URGENCYLEVEL IS NOT NULL THEN
        :NEW.URGENCYLEVEL := UPPER(:NEW.URGENCYLEVEL);
    END IF;
END;
/

-- TRG_CAT_MISSINGALERTS_BI：插入失踪预警时自动生成主键、默认预警时间和默认状态。
CREATE OR REPLACE TRIGGER TRG_CAT_MISSINGALERTS_BI
BEFORE INSERT ON CAT_MISSINGALERTS
FOR EACH ROW
BEGIN
    IF :NEW.ALERTID IS NULL THEN
        :NEW.ALERTID := LOWER(RAWTOHEX(SYS_GUID()));
    END IF;

    :NEW.ALERTTIME := NVL(:NEW.ALERTTIME, SYSDATE);
    :NEW.ALERTSTATUS := UPPER(NVL(:NEW.ALERTSTATUS, 'PROCESSING'));
END;
/

-- TRG_CAT_MISSINGALERTS_BU：更新失踪预警时统一状态格式，避免处理中/已寻回等值混乱。
CREATE OR REPLACE TRIGGER TRG_CAT_MISSINGALERTS_BU
BEFORE UPDATE ON CAT_MISSINGALERTS
FOR EACH ROW
BEGIN
    IF :NEW.ALERTSTATUS IS NOT NULL THEN
        :NEW.ALERTSTATUS := UPPER(:NEW.ALERTSTATUS);
    END IF;
END;
/

-- TRG_MED_HEALTHRECORDS_AUTO_REMINDER：插入或更新医疗记录时，如果存在下次处理日期，就自动生成后续提醒。
CREATE OR REPLACE TRIGGER TRG_MED_HEALTHRECORDS_AUTO_REMINDER
AFTER INSERT OR UPDATE OF NEXTDUEDATE, RECORDTYPE ON MED_HEALTHRECORDS
FOR EACH ROW
DECLARE
    V_REMINDERTYPE MED_REMINDERS.REMINDERTYPE%TYPE;
    V_EXISTS NUMBER;
BEGIN
    IF :NEW.NEXTDUEDATE IS NULL THEN
        RETURN;
    END IF;

    V_REMINDERTYPE :=
        CASE
            WHEN UPPER(:NEW.RECORDTYPE) IN ('VACCINE', 'DEWORM', 'STERILIZATION')
            THEN UPPER(:NEW.RECORDTYPE)
            ELSE 'RECHECK'
        END;

    SELECT COUNT(*)
    INTO V_EXISTS
    FROM MED_REMINDERS
    WHERE RECORDID = :NEW.RECORDID
      AND REMINDERTYPE = V_REMINDERTYPE;

    IF V_EXISTS = 0 THEN
        INSERT INTO MED_REMINDERS (
            REMINDERID,
            RECORDID,
            CATID,
            REMINDERTYPE,
            RECEIVERUSERID,
            REMINDERTIME,
            SENDSTATUS
        ) VALUES (
            LOWER(RAWTOHEX(SYS_GUID())),
            :NEW.RECORDID,
            :NEW.CATID,
            V_REMINDERTYPE,
            NULL,
            :NEW.NEXTDUEDATE,
            'PENDING'
        );
    END IF;
END;
/

-- 这一段定义包接口，对外提供新增、更新、状态流转等业务操作。
PROMPT Creating PL/SQL package specification...;

CREATE OR REPLACE PACKAGE PKG_RESCUE_141516 AS

    -- 14：医疗提醒相关操作
    -- 输入医疗记录、猫咪、接收人和提醒时间，创建一条新的提醒记录。
    PROCEDURE CREATE_REMINDER(
        P_RECORDID       IN MED_REMINDERS.RECORDID%TYPE,
        P_CATID          IN MED_REMINDERS.CATID%TYPE,
        P_REMINDERTYPE   IN MED_REMINDERS.REMINDERTYPE%TYPE,
        P_RECEIVERUSERID IN MED_REMINDERS.RECEIVERUSERID%TYPE,
        P_REMINDERTIME   IN MED_REMINDERS.REMINDERTIME%TYPE,
        O_REMINDERID     OUT MED_REMINDERS.REMINDERID%TYPE
    );

    -- 把提醒推进到“已发送”，用于消息已经发给接收人的场景。
    PROCEDURE MARK_REMINDER_SENT(
        P_REMINDERID IN MED_REMINDERS.REMINDERID%TYPE
    );

    -- 把提醒推进到“已完成”，表示这个后续护理事项已经处理结束。
    PROCEDURE COMPLETE_REMINDER(
        P_REMINDERID IN MED_REMINDERS.REMINDERID%TYPE
    );

    -- 15：紧急救助上报相关操作
    -- 普通用户提交救助上报，记录区域、动物类型、图片和紧急等级。
    PROCEDURE SUBMIT_EMERGENCY_REPORT(
        P_REPORTERUSERID IN EMERGENCY_REPORTS.REPORTERUSERID%TYPE,
        P_AREAID         IN EMERGENCY_REPORTS.AREAID%TYPE,
        P_ANIMALTYPE     IN EMERGENCY_REPORTS.ANIMALTYPE%TYPE,
        P_PHOTOURL       IN EMERGENCY_REPORTS.PHOTOURL%TYPE,
        P_LONGITUDE      IN EMERGENCY_REPORTS.LONGITUDE%TYPE,
        P_LATITUDE       IN EMERGENCY_REPORTS.LATITUDE%TYPE,
        P_URGENCYLEVEL   IN EMERGENCY_REPORTS.URGENCYLEVEL%TYPE,
        O_REPORTID       OUT EMERGENCY_REPORTS.REPORTID%TYPE
    );

    -- 管理员或志愿者接单后，把处理人写入上报记录。
    PROCEDURE ASSIGN_EMERGENCY_REPORT(
        P_REPORTID      IN EMERGENCY_REPORTS.REPORTID%TYPE,
        P_HANDLERUSERID IN EMERGENCY_REPORTS.HANDLERUSERID%TYPE
    );

    -- 更新紧急上报的处理状态和处理结果，形成闭环流程。
    PROCEDURE UPDATE_EMERGENCY_STATUS(
        P_REPORTID       IN EMERGENCY_REPORTS.REPORTID%TYPE,
        P_PROCESSSTATUS  IN EMERGENCY_REPORTS.PROCESSSTATUS%TYPE,
        P_PROCESSRESULT  IN EMERGENCY_REPORTS.PROCESSRESULT%TYPE
    );

    -- 16：失踪预警相关操作
    -- 创建猫咪失踪预警，记录最后目击信息、阈值和当前处理人。
    PROCEDURE CREATE_MISSING_ALERT(
        P_CATID             IN CAT_MISSINGALERTS.CATID%TYPE,
        P_LASTSIGHTINGID    IN CAT_MISSINGALERTS.LASTSIGHTINGID%TYPE,
        P_LASTSIGHTINGTIME  IN CAT_MISSINGALERTS.LASTSIGHTINGTIME%TYPE,
        P_THRESHOLDDAYS     IN CAT_MISSINGALERTS.THRESHOLDDAYS%TYPE,
        P_HANDLERUSERID     IN CAT_MISSINGALERTS.HANDLERUSERID%TYPE,
        P_REMARK            IN CAT_MISSINGALERTS.REMARK%TYPE,
        O_ALERTID           OUT CAT_MISSINGALERTS.ALERTID%TYPE
    );

    -- 更新失踪预警状态和处理备注，支持处理中、已寻回、已关闭。
    PROCEDURE UPDATE_MISSING_STATUS(
        P_ALERTID       IN CAT_MISSINGALERTS.ALERTID%TYPE,
        P_ALERTSTATUS   IN CAT_MISSINGALERTS.ALERTSTATUS%TYPE,
        P_HANDLERUSERID IN CAT_MISSINGALERTS.HANDLERUSERID%TYPE,
        P_REMARK        IN CAT_MISSINGALERTS.REMARK%TYPE
    );

    -- 根据医疗记录批量补生成后续提醒，适合初始化或补漏。
    PROCEDURE AUTO_CREATE_REMINDERS_FROM_HEALTH;

END PKG_RESCUE_141516;
/

-- 这一段是包体实现，把上面声明的每个业务过程真正写出来。
PROMPT Creating PL/SQL package body...;

CREATE OR REPLACE PACKAGE BODY PKG_RESCUE_141516 AS

    -- 统一生成 36 位字符串主键，适配你们现有的 VARCHAR2(36) 主键设计。
    FUNCTION NEW_ID RETURN VARCHAR2 IS
    BEGIN
        RETURN LOWER(RAWTOHEX(SYS_GUID()));
    END NEW_ID;

    -- 统一的状态校验函数，避免把不合法的状态写进数据库。
    PROCEDURE ASSERT_STATUS(
        P_VALUE IN VARCHAR2,
        P_ALLOWED IN VARCHAR2,
        P_ERROR_CODE IN NUMBER,
        P_ERROR_MESSAGE IN VARCHAR2
    ) AS
    BEGIN
        IF P_VALUE IS NULL OR INSTR(',' || P_ALLOWED || ',', ',' || P_VALUE || ',') = 0 THEN
            RAISE_APPLICATION_ERROR(P_ERROR_CODE, P_ERROR_MESSAGE || ': ' || P_VALUE);
        END IF;
    END ASSERT_STATUS;

    -- 14. 新建医疗提醒，来源可以是医疗记录，也可以是手工创建。
    PROCEDURE CREATE_REMINDER(
        P_RECORDID       IN MED_REMINDERS.RECORDID%TYPE,
        P_CATID          IN MED_REMINDERS.CATID%TYPE,
        P_REMINDERTYPE   IN MED_REMINDERS.REMINDERTYPE%TYPE,
        P_RECEIVERUSERID IN MED_REMINDERS.RECEIVERUSERID%TYPE,
        P_REMINDERTIME   IN MED_REMINDERS.REMINDERTIME%TYPE,
        O_REMINDERID     OUT MED_REMINDERS.REMINDERID%TYPE
    ) AS
    BEGIN
        -- 先检查提醒类型是否合法，再插入提醒记录。
        ASSERT_STATUS(
            UPPER(P_REMINDERTYPE),
            'VACCINE,DEWORM,STERILIZATION,RECHECK,OTHER',
            -20100,
            '提醒类型必须是 VACCINE, DEWORM, STERILIZATION, RECHECK, OTHER 之一'
        );

        O_REMINDERID := NEW_ID();

        INSERT INTO MED_REMINDERS (
            REMINDERID,
            RECORDID,
            CATID,
            REMINDERTYPE,
            RECEIVERUSERID,
            REMINDERTIME,
            SENDSTATUS
        ) VALUES (
            O_REMINDERID,
            P_RECORDID,
            P_CATID,
            UPPER(P_REMINDERTYPE),
            P_RECEIVERUSERID,
            NVL(P_REMINDERTIME, SYSDATE),
            'PENDING'
        );
    END CREATE_REMINDER;

    -- 14. 把提醒标记成已发送，表示消息已经发给接收人。
    PROCEDURE MARK_REMINDER_SENT(
        P_REMINDERID IN MED_REMINDERS.REMINDERID%TYPE
    ) AS
    BEGIN
        -- 直接把提醒状态改为 SENT，表示消息已发出。
        UPDATE MED_REMINDERS
        SET SENDSTATUS = 'SENT'
        WHERE REMINDERID = P_REMINDERID;

        IF SQL%ROWCOUNT = 0 THEN
            RAISE_APPLICATION_ERROR(-20101, '提醒不存在');
        END IF;
    END MARK_REMINDER_SENT;

    -- 14. 把提醒标记成已完成，表示这个后续处理已经结束。
    PROCEDURE COMPLETE_REMINDER(
        P_REMINDERID IN MED_REMINDERS.REMINDERID%TYPE
    ) AS
    BEGIN
        -- 直接把提醒状态改为 COMPLETED，表示后续处理已经结束。
        UPDATE MED_REMINDERS
        SET SENDSTATUS = 'COMPLETED'
        WHERE REMINDERID = P_REMINDERID;

        IF SQL%ROWCOUNT = 0 THEN
            RAISE_APPLICATION_ERROR(-20102, '提醒不存在');
        END IF;
    END COMPLETE_REMINDER;

    -- 15. 普通用户提交紧急救助上报。
    PROCEDURE SUBMIT_EMERGENCY_REPORT(
        P_REPORTERUSERID IN EMERGENCY_REPORTS.REPORTERUSERID%TYPE,
        P_AREAID         IN EMERGENCY_REPORTS.AREAID%TYPE,
        P_ANIMALTYPE     IN EMERGENCY_REPORTS.ANIMALTYPE%TYPE,
        P_PHOTOURL       IN EMERGENCY_REPORTS.PHOTOURL%TYPE,
        P_LONGITUDE      IN EMERGENCY_REPORTS.LONGITUDE%TYPE,
        P_LATITUDE       IN EMERGENCY_REPORTS.LATITUDE%TYPE,
        P_URGENCYLEVEL   IN EMERGENCY_REPORTS.URGENCYLEVEL%TYPE,
        O_REPORTID       OUT EMERGENCY_REPORTS.REPORTID%TYPE
    ) AS
    BEGIN
        -- 先校验紧急等级，再生成新上报记录，默认状态为 SUBMITTED。
        ASSERT_STATUS(
            UPPER(P_URGENCYLEVEL),
            'LOW,MEDIUM,HIGH,CRITICAL',
            -20103,
            '紧急等级必须是 LOW, MEDIUM, HIGH, CRITICAL 之一'
        );

        O_REPORTID := NEW_ID();

        INSERT INTO EMERGENCY_REPORTS (
            REPORTID,
            REPORTERUSERID,
            AREAID,
            ANIMALTYPE,
            PHOTOURL,
            LONGITUDE,
            LATITUDE,
            REPORTTIME,
            URGENCYLEVEL,
            PROCESSSTATUS,
            HANDLERUSERID,
            PROCESSRESULT
        ) VALUES (
            O_REPORTID,
            P_REPORTERUSERID,
            P_AREAID,
            UPPER(P_ANIMALTYPE),
            P_PHOTOURL,
            P_LONGITUDE,
            P_LATITUDE,
            SYSDATE,
            UPPER(P_URGENCYLEVEL),
            'SUBMITTED',
            NULL,
            NULL
        );
    END SUBMIT_EMERGENCY_REPORT;

    -- 15. 管理员或志愿者接单，分配处理人。
    PROCEDURE ASSIGN_EMERGENCY_REPORT(
        P_REPORTID      IN EMERGENCY_REPORTS.REPORTID%TYPE,
        P_HANDLERUSERID IN EMERGENCY_REPORTS.HANDLERUSERID%TYPE
    ) AS
    BEGIN
        -- 分配处理人，并把状态改成 ASSIGNED。
        UPDATE EMERGENCY_REPORTS
        SET HANDLERUSERID = P_HANDLERUSERID,
            PROCESSSTATUS = 'ASSIGNED'
        WHERE REPORTID = P_REPORTID;

        IF SQL%ROWCOUNT = 0 THEN
            RAISE_APPLICATION_ERROR(-20104, '紧急救助上报不存在');
        END IF;
    END ASSIGN_EMERGENCY_REPORT;

    -- 15. 更新紧急上报的处理状态和结果。
    PROCEDURE UPDATE_EMERGENCY_STATUS(
        P_REPORTID       IN EMERGENCY_REPORTS.REPORTID%TYPE,
        P_PROCESSSTATUS  IN EMERGENCY_REPORTS.PROCESSSTATUS%TYPE,
        P_PROCESSRESULT  IN EMERGENCY_REPORTS.PROCESSRESULT%TYPE
    ) AS
    BEGIN
        -- 更新紧急上报的流转状态和最终处理结果。
        ASSERT_STATUS(
            UPPER(P_PROCESSSTATUS),
            'SUBMITTED,ASSIGNED,PROCESSING,RESOLVED,CLOSED',
            -20105,
            '处理状态必须是 SUBMITTED, ASSIGNED, PROCESSING, RESOLVED, CLOSED 之一'
        );

        UPDATE EMERGENCY_REPORTS
        SET PROCESSSTATUS = UPPER(P_PROCESSSTATUS),
            PROCESSRESULT = P_PROCESSRESULT
        WHERE REPORTID = P_REPORTID;

        IF SQL%ROWCOUNT = 0 THEN
            RAISE_APPLICATION_ERROR(-20106, '紧急救助上报不存在');
        END IF;
    END UPDATE_EMERGENCY_STATUS;

    -- 16. 创建失踪预警，记录最后目击时间、阈值天数和处理人。
    PROCEDURE CREATE_MISSING_ALERT(
        P_CATID             IN CAT_MISSINGALERTS.CATID%TYPE,
        P_LASTSIGHTINGID    IN CAT_MISSINGALERTS.LASTSIGHTINGID%TYPE,
        P_LASTSIGHTINGTIME  IN CAT_MISSINGALERTS.LASTSIGHTINGTIME%TYPE,
        P_THRESHOLDDAYS     IN CAT_MISSINGALERTS.THRESHOLDDAYS%TYPE,
        P_HANDLERUSERID     IN CAT_MISSINGALERTS.HANDLERUSERID%TYPE,
        P_REMARK            IN CAT_MISSINGALERTS.REMARK%TYPE,
        O_ALERTID           OUT CAT_MISSINGALERTS.ALERTID%TYPE
    ) AS
    BEGIN
        -- 阈值天数不能为负数或 0，防止创建无意义的预警。
        IF P_THRESHOLDDAYS IS NOT NULL AND P_THRESHOLDDAYS <= 0 THEN
            RAISE_APPLICATION_ERROR(-20109, '阈值天数必须大于 0');
        END IF;

        -- 生成失踪预警，默认状态是 PROCESSING。
        O_ALERTID := NEW_ID();

        INSERT INTO CAT_MISSINGALERTS (
            ALERTID,
            CATID,
            LASTSIGHTINGID,
            LASTSIGHTINGTIME,
            THRESHOLDDAYS,
            ALERTTIME,
            ALERTSTATUS,
            HANDLERUSERID,
            CLOSETIME,
            REMARK
        ) VALUES (
            O_ALERTID,
            P_CATID,
            P_LASTSIGHTINGID,
            P_LASTSIGHTINGTIME,
            NVL(P_THRESHOLDDAYS, 7),
            SYSDATE,
            'PROCESSING',
            P_HANDLERUSERID,
            NULL,
            P_REMARK
        );
    END CREATE_MISSING_ALERT;

    -- 16. 更新失踪预警状态，支持处理中、已寻回、已关闭。
    PROCEDURE UPDATE_MISSING_STATUS(
        P_ALERTID       IN CAT_MISSINGALERTS.ALERTID%TYPE,
        P_ALERTSTATUS   IN CAT_MISSINGALERTS.ALERTSTATUS%TYPE,
        P_HANDLERUSERID IN CAT_MISSINGALERTS.HANDLERUSERID%TYPE,
        P_REMARK        IN CAT_MISSINGALERTS.REMARK%TYPE
    ) AS
    BEGIN
        -- 校验状态后再更新，确保只能流转到允许的预警状态。
        ASSERT_STATUS(
            UPPER(P_ALERTSTATUS),
            'PROCESSING,FOUND,CLOSED',
            -20107,
            '失踪预警状态必须是 PROCESSING, FOUND, CLOSED 之一'
        );

        UPDATE CAT_MISSINGALERTS
        SET ALERTSTATUS = UPPER(P_ALERTSTATUS),
            HANDLERUSERID = NVL(P_HANDLERUSERID, HANDLERUSERID),
            CLOSETIME = CASE
                WHEN UPPER(P_ALERTSTATUS) IN ('FOUND', 'CLOSED') THEN SYSDATE
                ELSE CLOSETIME
            END,
            REMARK = P_REMARK
        WHERE ALERTID = P_ALERTID;

        IF SQL%ROWCOUNT = 0 THEN
            RAISE_APPLICATION_ERROR(-20108, '失踪预警不存在');
        END IF;
    END UPDATE_MISSING_STATUS;

    -- 批处理：根据医疗记录补生成提醒，防止漏掉后续护理事项。
    PROCEDURE AUTO_CREATE_REMINDERS_FROM_HEALTH AS
    BEGIN
        -- 扫描医疗记录，给存在下次处理日期的记录自动补生成提醒。
        INSERT INTO MED_REMINDERS (
            REMINDERID,
            RECORDID,
            CATID,
            REMINDERTYPE,
            RECEIVERUSERID,
            REMINDERTIME,
            SENDSTATUS
        )
        SELECT
            LOWER(RAWTOHEX(SYS_GUID())),
            H.RECORDID,
            H.CATID,
            CASE
                WHEN UPPER(H.RECORDTYPE) IN ('VACCINE', 'DEWORM', 'STERILIZATION')
                THEN UPPER(H.RECORDTYPE)
                ELSE 'RECHECK'
            END,
            NULL,
            H.NEXTDUEDATE,
            'PENDING'
        FROM MED_HEALTHRECORDS H
        WHERE H.NEXTDUEDATE IS NOT NULL
          AND NOT EXISTS (
              SELECT 1
              FROM MED_REMINDERS R
              WHERE R.RECORDID = H.RECORDID
                AND R.REMINDERTYPE =
                    CASE
                        WHEN UPPER(H.RECORDTYPE) IN ('VACCINE', 'DEWORM', 'STERILIZATION')
                        THEN UPPER(H.RECORDTYPE)
                        ELSE 'RECHECK'
                    END
          );
    END AUTO_CREATE_REMINDERS_FROM_HEALTH;

END PKG_RESCUE_141516;
/

SHOW ERRORS PACKAGE PKG_RESCUE_141516;
SHOW ERRORS PACKAGE BODY PKG_RESCUE_141516;

PROMPT ===== Rescue 14/15/16 programming layer complete =====;
