SELECT USERID, USERNAME, STATUS
FROM SYS_USERS
ORDER BY USERNAME;

SELECT *
FROM VW_USER_ROLE_PROFILE
WHERE UPPER(USERNAME) LIKE '%ADMIN%';

UPDATE SYS_USERS
SET STATUS = 'DISABLED'
WHERE USERID = :USER_ID;

UPDATE SYS_USERS
SET STATUS = 'ACTIVE'
WHERE USERID = :USER_ID;
