SET DEFINE OFF;
SET SERVEROUTPUT ON;

-- A组成员1高级 SQL：用户-角色视图与用户筛选索引。
-- 约定：后端 UserRepository 查询 VW_USER_ROLE_PROFILE（含 PASSWORDHASH，仅服务端使用，API 不回传）。
-- 状态契约：STATUS = ACTIVE | DISABLED；VERIFYSTATUS = VERIFIED | UNVERIFIED。

CREATE OR REPLACE PROCEDURE create_index_if_not_exists(p_sql IN VARCHAR2) AS
BEGIN
    EXECUTE IMMEDIATE p_sql;
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

CREATE OR REPLACE VIEW VW_USER_ROLE_PROFILE AS
SELECT u.USERID,
       u.ROLEID,
       u.USERNAME,
       u.PASSWORDHASH,
       u.REALNAME,
       u.STUDENTNO,
       u.PHONE,
       u.VERIFYSTATUS,
       u.STATUS,
       r.ROLENAME,
       r.PERMISSIONSCOPE
FROM SYS_USERS u
JOIN SYS_ROLES r ON r.ROLEID = u.ROLEID;

-- 活跃用户简表：列表筛选演示（不含密码哈希）。
CREATE OR REPLACE VIEW VW_ACTIVE_USER_SUMMARIES AS
SELECT USERID,
       ROLEID,
       USERNAME,
       REALNAME,
       STUDENTNO,
       PHONE,
       VERIFYSTATUS,
       STATUS,
       ROLENAME,
       PERMISSIONSCOPE
FROM VW_USER_ROLE_PROFILE
WHERE STATUS = 'ACTIVE';

BEGIN
    create_index_if_not_exists(
        'CREATE INDEX IDX_SYS_USERS_STATUS_ROLEID ON SYS_USERS (STATUS, ROLEID)');
    create_index_if_not_exists(
        'CREATE INDEX IDX_SYS_USERS_USERNAME_UPPER ON SYS_USERS (UPPER(USERNAME))');
END;
/

PROMPT A-group member1 advanced SQL ready.
/
