CREATE OR REPLACE VIEW VW_USER_ROLE_PROFILE AS
SELECT u.USERID,
       u.ROLEID,
       u.USERNAME,
       u.REALNAME,
       u.STUDENTNO,
       u.PHONE,
       u.VERIFYSTATUS,
       u.STATUS,
       r.ROLENAME,
       r.PERMISSIONSCOPE
FROM SYS_USERS u
JOIN SYS_ROLES r ON r.ROLEID = u.ROLEID;

CREATE INDEX IDX_SYS_USERS_STATUS_ROLEID ON SYS_USERS (STATUS, ROLEID);
CREATE INDEX IDX_SYS_USERS_USERNAME_UPPER ON SYS_USERS (UPPER(USERNAME));
