SET DEFINE OFF;
SET SERVEROUTPUT ON;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;

PROMPT ===== Normalizing and enforcing shared field contracts =====;

/*
  这份脚本用于已有数据库的契约迁移，也会被 setup_all.sql 调用。
  先把仓库早期脚本中出现过的中文/旧英文值迁移为统一编码，再按约束名
  幂等增加 CHECK。CMS、投票和寄养等尚未定稿的字典字段暂不纳入本次迁移。
*/
DECLARE
    PROCEDURE add_check(
        p_table_name IN VARCHAR2,
        p_constraint_name IN VARCHAR2,
        p_expression IN VARCHAR2
    ) IS
        v_exists NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_exists
        FROM USER_CONSTRAINTS
        WHERE CONSTRAINT_NAME = UPPER(p_constraint_name);

        IF v_exists = 0 THEN
            EXECUTE IMMEDIATE
                'ALTER TABLE ' || p_table_name ||
                ' ADD CONSTRAINT ' || p_constraint_name ||
                ' CHECK (' || p_expression || ')';
        END IF;
    END;
BEGIN
    /* 已知旧值迁移。未知值不会被静默改写，随后添加约束时会明确失败。 */
    UPDATE SYS_ROLES
       SET ROLENAME = CASE TRIM(UPPER(ROLENAME))
           WHEN '管理员' THEN 'ADMIN'
           WHEN '志愿者' THEN 'VOLUNTEER'
           WHEN '普通用户' THEN 'USER'
           WHEN '兽医' THEN 'VET'
           WHEN '演示志愿者' THEN 'VOLUNTEER'
           ELSE TRIM(UPPER(ROLENAME))
       END
     WHERE ROLENAME IS NOT NULL;

    UPDATE SYS_USERS SET STATUS = TRIM(UPPER(STATUS)) WHERE STATUS IS NOT NULL;
    UPDATE SYS_USERS SET VERIFYSTATUS = TRIM(UPPER(VERIFYSTATUS)) WHERE VERIFYSTATUS IS NOT NULL;

    UPDATE MAP_CAMPUSAREAS
       SET AREATYPE = CASE TRIM(UPPER(AREATYPE))
           WHEN '校区' THEN 'CAMPUS'
           WHEN '公共区域' THEN 'PUBLIC_AREA'
           WHEN '活动区域' THEN 'ACTIVITY_AREA'
           ELSE TRIM(UPPER(AREATYPE))
       END,
           RISKLEVEL = CASE TRIM(UPPER(RISKLEVEL))
           WHEN '低' THEN 'LOW'
           WHEN '中' THEN 'MEDIUM'
           WHEN '高' THEN 'HIGH'
           ELSE TRIM(UPPER(RISKLEVEL))
       END
     WHERE AREATYPE IS NOT NULL OR RISKLEVEL IS NOT NULL;

    UPDATE CAT_CATS
       SET GENDER = TRIM(UPPER(GENDER)),
           STERILIZEDFLAG = STERILIZEDFLAG,
           EARTIPFLAG = EARTIPFLAG,
           LIFESTATUS = CASE TRIM(UPPER(LIFESTATUS))
               WHEN 'ALIVE' THEN 'ON_CAMPUS'
               WHEN '在校' THEN 'ON_CAMPUS'
               ELSE TRIM(UPPER(LIFESTATUS))
           END,
           ARCHIVESTATUS = CASE TRIM(UPPER(ARCHIVESTATUS))
               WHEN 'ACTIVE' THEN 'PUBLISHED'
               WHEN '公开' THEN 'PUBLISHED'
               ELSE TRIM(UPPER(ARCHIVESTATUS))
           END
     WHERE GENDER IS NOT NULL OR STERILIZEDFLAG IS NOT NULL OR EARTIPFLAG IS NOT NULL
        OR LIFESTATUS IS NOT NULL OR ARCHIVESTATUS IS NOT NULL;

    UPDATE CAT_PHOTOS SET ISPRIMARY = ISPRIMARY;

    UPDATE MAP_SERVICEPOINTS
       SET POINTTYPE = CASE TRIM(UPPER(POINTTYPE))
           WHEN '喂食点' THEN 'FEEDING'
           WHEN '投喂点' THEN 'FEEDING'
           WHEN '猫窝' THEN 'NEST'
           WHEN '活动点' THEN 'ACTIVITY'
           ELSE TRIM(UPPER(POINTTYPE))
       END,
           FACILITYSTATUS = CASE TRIM(UPPER(FACILITYSTATUS))
           WHEN '正常' THEN 'ACTIVE'
           WHEN 'NORMAL' THEN 'ACTIVE'
           WHEN '需定期巡查' THEN 'MAINTENANCE'
           ELSE TRIM(UPPER(FACILITYSTATUS))
       END
     WHERE POINTTYPE IS NOT NULL OR FACILITYSTATUS IS NOT NULL;

    UPDATE NEST_MAINTENANCERECORDS
       SET MATERIALTYPE = CASE TRIM(UPPER(MATERIALTYPE))
           WHEN '保温箱' THEN 'INSULATION_BOX'
           WHEN '食盆' THEN 'FOOD_BOWL'
           WHEN '水盆' THEN 'WATER_BOWL'
           ELSE TRIM(UPPER(MATERIALTYPE))
       END,
           WEATHERCONDITION = CASE TRIM(UPPER(WEATHERCONDITION))
           WHEN '晴' THEN 'SUNNY'
           WHEN '多云' THEN 'CLOUDY'
           WHEN '雨' THEN 'RAINY'
           WHEN '雪' THEN 'SNOWY'
           ELSE TRIM(UPPER(WEATHERCONDITION))
       END,
           DAMAGELEVEL = CASE TRIM(UPPER(DAMAGELEVEL))
           WHEN '无' THEN 'NONE'
           WHEN '轻微' THEN 'MINOR'
           WHEN '严重' THEN 'MAJOR'
           ELSE TRIM(UPPER(DAMAGELEVEL))
       END,
           ACTIONTYPE = CASE TRIM(UPPER(ACTIONTYPE))
           WHEN '清理' THEN 'CLEAN'
           WHEN '维修' THEN 'REPAIR'
           WHEN '更换' THEN 'REPLACE'
           ELSE TRIM(UPPER(ACTIONTYPE))
       END;

    UPDATE FUND_DONATIONS
       SET PAYMETHOD = TRIM(UPPER(PAYMETHOD))
     WHERE PAYMETHOD IS NOT NULL;
    UPDATE FUND_FINANCERECORDS
       SET RECORDTYPE = TRIM(UPPER(RECORDTYPE))
     WHERE RECORDTYPE IS NOT NULL;

    UPDATE CAT_MATCHRECORDS SET CONFIRMSTATUS = TRIM(UPPER(CONFIRMSTATUS)) WHERE CONFIRMSTATUS IS NOT NULL;
    UPDATE TNR_CASES SET CURRENTSTATUS = TRIM(UPPER(CURRENTSTATUS)) WHERE CURRENTSTATUS IS NOT NULL;
    UPDATE TNR_STATUSLOGS
       SET FROMSTATUS = TRIM(UPPER(FROMSTATUS)), TOSTATUS = TRIM(UPPER(TOSTATUS));
    UPDATE MED_HEALTHRECORDS SET RECORDTYPE = TRIM(UPPER(RECORDTYPE)) WHERE RECORDTYPE IS NOT NULL;
    UPDATE MED_REMINDERS
       SET REMINDERTYPE = TRIM(UPPER(REMINDERTYPE)), SENDSTATUS = TRIM(UPPER(SENDSTATUS));
    UPDATE ADOPT_APPLICATIONS SET CURRENTSTATUS = TRIM(UPPER(CURRENTSTATUS)) WHERE CURRENTSTATUS IS NOT NULL;
    UPDATE ADOPT_VISITS SET VISITTYPE = TRIM(UPPER(VISITTYPE)) WHERE VISITTYPE IS NOT NULL;
    UPDATE VOL_VOLUNTEERS
       SET CREDITLEVEL = TRIM(UPPER(CREDITLEVEL)), ACTIVESTATUS = TRIM(UPPER(ACTIVESTATUS));
    UPDATE VOL_SHIFTS SET SHIFTSTATUS = TRIM(UPPER(SHIFTSTATUS)) WHERE SHIFTSTATUS IS NOT NULL;
    UPDATE VOL_CHECKINS SET CHECKINSTATUS = TRIM(UPPER(CHECKINSTATUS)) WHERE CHECKINSTATUS IS NOT NULL;
    UPDATE FOSTER_FOSTERNEEDS SET NEEDSTATUS = TRIM(UPPER(NEEDSTATUS)) WHERE NEEDSTATUS IS NOT NULL;
    UPDATE FOSTER_DAILYREPORTS SET ALERTFLAG = ALERTFLAG;
    UPDATE VOTE_NAMINGCANDIDATES SET WINFLAG = WINFLAG;
    UPDATE FUND_CROWDFUNDINGPROJECTS SET PROJECTSTATUS = TRIM(UPPER(PROJECTSTATUS)) WHERE PROJECTSTATUS IS NOT NULL;
    UPDATE FUND_DONATIONS SET PUBLICFLAG = PUBLICFLAG;
    UPDATE FUND_FINANCERECORDS SET AUDITSTATUS = TRIM(UPPER(AUDITSTATUS)) WHERE AUDITSTATUS IS NOT NULL;
    UPDATE CMS_NOTICES SET TOPFLAG = TOPFLAG;
    UPDATE CMS_ARTICLES SET TOPFLAG = TOPFLAG;
    UPDATE CAT_MISSINGALERTS
       SET ALERTSTATUS = TRIM(UPPER(ALERTSTATUS));
    UPDATE EMERGENCY_REPORTS
       SET ANIMALTYPE = TRIM(UPPER(ANIMALTYPE)),
           URGENCYLEVEL = TRIM(UPPER(URGENCYLEVEL)),
           PROCESSSTATUS = TRIM(UPPER(PROCESSSTATUS));
    UPDATE VOL_CREDITLOGS SET CREDITLEVELAFTER = TRIM(UPPER(CREDITLEVELAFTER)) WHERE CREDITLEVELAFTER IS NOT NULL;
    UPDATE VOL_HANDOVERS
       SET HANDOVERTYPE = TRIM(UPPER(HANDOVERTYPE)),
           RELATEDTYPE = TRIM(UPPER(RELATEDTYPE)),
           HANDOVERSTATUS = TRIM(UPPER(HANDOVERSTATUS));
    UPDATE USER_BLACKLIST
       SET REASONTYPE = CASE TRIM(UPPER(REASONTYPE))
           WHEN '违规领养' THEN 'ABANDONMENT'
           WHEN '恶意行为' THEN 'ANIMAL_ABUSE'
           WHEN '虚假信息' THEN 'FALSE_INFORMATION'
           ELSE TRIM(UPPER(REASONTYPE))
       END,
           BLACKLISTSTATUS = TRIM(UPPER(BLACKLISTSTATUS));
    UPDATE RPT_STATISTICSSNAPSHOTS
       SET METRICCODE = TRIM(UPPER(METRICCODE)),
           DIMENSIONTYPE = TRIM(UPPER(DIMENSIONTYPE)),
           UNIT = TRIM(UPPER(UNIT));

    /* 角色枚举从三类扩展为四类；旧版同名约束需要先刷新，否则会被幂等逻辑跳过。 */
    DECLARE
        v_role_constraint NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_role_constraint
        FROM USER_CONSTRAINTS
        WHERE CONSTRAINT_NAME = 'CK_SYS_ROLES_NAME';
        IF v_role_constraint > 0 THEN
            EXECUTE IMMEDIATE 'ALTER TABLE SYS_ROLES DROP CONSTRAINT CK_SYS_ROLES_NAME';
        END IF;
    END;

    add_check('SYS_ROLES', 'CK_SYS_ROLES_NAME', 'ROLENAME IN (''ADMIN'',''VOLUNTEER'',''USER'',''VET'')');
    add_check('SYS_USERS', 'CK_SYS_USERS_STATUS', 'STATUS IN (''ACTIVE'',''DISABLED'')');
    add_check('SYS_USERS', 'CK_SYS_USERS_VERIFY', 'VERIFYSTATUS IN (''VERIFIED'',''UNVERIFIED'')');
    add_check('MAP_CAMPUSAREAS', 'CK_AREA_TYPE', 'AREATYPE IN (''CAMPUS'',''PUBLIC_AREA'',''ACTIVITY_AREA'',''GREENBELT'',''GATE'')');
    add_check('MAP_CAMPUSAREAS', 'CK_AREA_RISK', 'RISKLEVEL IN (''LOW'',''MEDIUM'',''HIGH'')');
    add_check('CAT_CATS', 'CK_CAT_GENDER', 'GENDER IN (''UNKNOWN'',''MALE'',''FEMALE'')');
    add_check('CAT_CATS', 'CK_CAT_STERILE', 'STERILIZEDFLAG IN (0,1)');
    add_check('CAT_CATS', 'CK_CAT_EARTIP', 'EARTIPFLAG IN (0,1)');
    add_check('CAT_CATS', 'CK_CAT_LIFE', 'LIFESTATUS IN (''ON_CAMPUS'',''MISSING'',''ADOPTED'',''DECEASED'')');
    add_check('CAT_CATS', 'CK_CAT_ARCHIVE', 'ARCHIVESTATUS IN (''DRAFT'',''PUBLISHED'',''ARCHIVED'')');
    add_check('CAT_PHOTOS', 'CK_PHOTO_PRIMARY', 'ISPRIMARY IN (0,1)');
    add_check('MAP_SERVICEPOINTS', 'CK_POINT_TYPE', 'POINTTYPE IN (''FEEDING'',''NEST'',''ACTIVITY'')');
    add_check('MAP_SERVICEPOINTS', 'CK_POINT_STATUS', 'FACILITYSTATUS IN (''ACTIVE'',''INACTIVE'',''MAINTENANCE'')');
    add_check('MAP_SERVICEPOINTS', 'CK_POINT_LON', 'LONGITUDE BETWEEN -180 AND 180');
    add_check('MAP_SERVICEPOINTS', 'CK_POINT_LAT', 'LATITUDE BETWEEN -90 AND 90');
    add_check('MAP_SERVICEPOINTS', 'CK_POINT_COORD', '(LONGITUDE IS NULL AND LATITUDE IS NULL) OR (LONGITUDE IS NOT NULL AND LATITUDE IS NOT NULL)');
    add_check('CAT_SIGHTINGS', 'CK_SIGHT_LON', 'LONGITUDE BETWEEN -180 AND 180');
    add_check('CAT_SIGHTINGS', 'CK_SIGHT_LAT', 'LATITUDE BETWEEN -90 AND 90');
    add_check('CAT_SIGHTINGS', 'CK_SIGHT_COORD', '(LONGITUDE IS NULL AND LATITUDE IS NULL) OR (LONGITUDE IS NOT NULL AND LATITUDE IS NOT NULL)');
    add_check('CAT_MATCHRECORDS', 'CK_MATCH_STATUS', 'CONFIRMSTATUS IN (''PENDING'',''CONFIRMED'',''REJECTED'')');
    add_check('TNR_CASES', 'CK_TNR_STATUS', 'CURRENTSTATUS IN (''DISCOVERED'',''CAPTURED'',''SURGERY'',''RECOVERING'',''RELEASED'',''CANCELLED'')');
    add_check('TNR_STATUSLOGS', 'CK_TNR_LOG_FROM', 'FROMSTATUS IN (''DISCOVERED'',''CAPTURED'',''SURGERY'',''RECOVERING'',''RELEASED'',''CANCELLED'')');
    add_check('TNR_STATUSLOGS', 'CK_TNR_LOG_TO', 'TOSTATUS IN (''DISCOVERED'',''CAPTURED'',''SURGERY'',''RECOVERING'',''RELEASED'',''CANCELLED'')');
    add_check('TNR_CASES', 'CK_TNR_COST', 'TOTALCOST >= 0');
    add_check('MED_HEALTHRECORDS', 'CK_MED_RECORD_TYPE', 'RECORDTYPE IN (''VACCINATION'',''CHECKUP'',''TREATMENT'',''SURGERY'',''DEWORMING'',''EMERGENCY'',''OTHER'')');
    add_check('MED_REMINDERS', 'CK_MED_REM_TYPE', 'REMINDERTYPE IN (''VACCINATION'',''CHECKUP'',''TREATMENT'',''SURGERY'',''DEWORMING'',''EMERGENCY'',''OTHER'')');
    add_check('MED_REMINDERS', 'CK_MED_SEND_STATUS', 'SENDSTATUS IN (''PENDING'',''SENT'',''COMPLETED'')');
    add_check('ADOPT_APPLICATIONS', 'CK_ADOPT_STATUS', 'CURRENTSTATUS IN (''PENDING'',''APPROVED'',''REJECTED'')');
    add_check('ADOPT_VISITS', 'CK_VISIT_TYPE', 'VISITTYPE IN (''INITIAL'',''FOLLOW_UP'',''FINAL'')');
    add_check('ADOPT_VISITS', 'CK_VISIT_PASS', 'PASSFLAG IN (0,1)');
    add_check('VOL_VOLUNTEERS', 'CK_VOL_CREDIT', 'CREDITLEVEL IN (''L1'',''L2'',''L3'')');
    add_check('VOL_VOLUNTEERS', 'CK_VOL_ACTIVE', 'ACTIVESTATUS IN (''ACTIVE'',''INACTIVE'')');
    add_check('VOL_SHIFTS', 'CK_SHIFT_STATUS', 'SHIFTSTATUS IN (''PLANNED'',''ASSIGNED'',''IN_PROGRESS'',''COMPLETED'',''MISSED'')');
    add_check('VOL_CHECKINS', 'CK_CHECKIN_STATUS', 'CHECKINSTATUS IN (''CHECKED_IN'',''LATE'')');
    add_check('FOSTER_FOSTERNEEDS', 'CK_FOSTER_STATUS', 'NEEDSTATUS IN (''OPEN'',''ASSIGNED'',''COMPLETED'',''CANCELLED'')');
    add_check('FOSTER_DAILYREPORTS', 'CK_FOSTER_ALERT', 'ALERTFLAG IN (0,1)');
    add_check('VOTE_NAMINGCANDIDATES', 'CK_VOTE_WIN', 'WINFLAG IN (0,1)');
    add_check('FUND_CROWDFUNDINGPROJECTS', 'CK_FUND_PROJECT_STATUS', 'PROJECTSTATUS IN (''ACTIVE'',''COMPLETED'',''CANCELLED'')');
    add_check('FUND_CROWDFUNDINGPROJECTS', 'CK_FUND_TARGET', 'TARGETAMOUNT >= 0');
    add_check('FUND_CROWDFUNDINGPROJECTS', 'CK_FUND_RAISED', 'RAISEDAMOUNT >= 0');
    add_check('FUND_DONATIONS', 'CK_DONATION_PUBLIC', 'PUBLICFLAG IN (0,1)');
    add_check('FUND_DONATIONS', 'CK_DONATION_AMOUNT', 'AMOUNT > 0');
    add_check('FUND_FINANCERECORDS', 'CK_FINANCE_AUDIT', 'AUDITSTATUS IN (''PENDING'',''APPROVED'',''REJECTED'')');
    add_check('FUND_FINANCERECORDS', 'CK_FINANCE_AMOUNT', 'AMOUNT >= 0');
    add_check('CMS_NOTICES', 'CK_NOTICE_TOP', 'TOPFLAG IN (0,1)');
    add_check('CMS_ARTICLES', 'CK_ARTICLE_TOP', 'TOPFLAG IN (0,1)');
    add_check('CAT_MISSINGALERTS', 'CK_MISSING_STATUS', 'ALERTSTATUS IN (''PROCESSING'',''FOUND'',''CLOSED'')');
    add_check('CAT_MISSINGALERTS', 'CK_MISSING_THRESHOLD', 'THRESHOLDDAYS > 0');
    add_check('EMERGENCY_REPORTS', 'CK_EMERGENCY_ANIMAL', 'ANIMALTYPE IN (''CAT'',''DOG'',''OTHER'')');
    add_check('EMERGENCY_REPORTS', 'CK_EMERGENCY_URG', 'URGENCYLEVEL IN (''LOW'',''MEDIUM'',''HIGH'',''CRITICAL'')');
    add_check('EMERGENCY_REPORTS', 'CK_EMERGENCY_PROCESS', 'PROCESSSTATUS IN (''SUBMITTED'',''ASSIGNED'',''PROCESSING'',''RESOLVED'',''CLOSED'')');
    add_check('EMERGENCY_REPORTS', 'CK_EMERGENCY_LON', 'LONGITUDE BETWEEN -180 AND 180');
    add_check('EMERGENCY_REPORTS', 'CK_EMERGENCY_LAT', 'LATITUDE BETWEEN -90 AND 90');
    add_check('EMERGENCY_REPORTS', 'CK_EMERGENCY_COORD', '(LONGITUDE IS NULL AND LATITUDE IS NULL) OR (LONGITUDE IS NOT NULL AND LATITUDE IS NOT NULL)');
    add_check('VOL_CREDITLOGS', 'CK_CREDIT_LEVEL_AFTER', 'CREDITLEVELAFTER IN (''L1'',''L2'',''L3'')');
    add_check('VOL_HANDOVERS', 'CK_HANDOVER_TYPE', 'HANDOVERTYPE IN (''TASK'',''SHIFT'')');
    add_check('VOL_HANDOVERS', 'CK_HANDOVER_RELATED', 'RELATEDTYPE = ''SHIFT''');
    add_check('VOL_HANDOVERS', 'CK_HANDOVER_STATUS', 'HANDOVERSTATUS IN (''PENDING'',''CONFIRMED'',''REJECTED'',''CANCELLED'')');
    add_check('USER_BLACKLIST', 'CK_BLACKLIST_REASON', 'REASONTYPE IN (''ABANDONMENT'',''ANIMAL_ABUSE'',''FALSE_INFORMATION'',''OTHER'')');
    add_check('USER_BLACKLIST', 'CK_BLACKLIST_STATUS', 'BLACKLISTSTATUS IN (''ACTIVE'',''RELEASED'')');
    add_check('RPT_STATISTICSSNAPSHOTS', 'CK_RPT_METRIC', 'METRICCODE IN (''TOTAL_DONATION'',''TOTAL_EXPENSE'',''NET_BALANCE'',''DONATION_COUNT'')');
    add_check('RPT_STATISTICSSNAPSHOTS', 'CK_RPT_DIM', 'DIMENSIONTYPE IN (''PROJECT'',''MONTH'',''CAT'')');
    add_check('RPT_STATISTICSSNAPSHOTS', 'CK_RPT_UNIT', 'UNIT IN (''CNY'',''COUNT'')');
    add_check('NEST_MAINTENANCERECORDS', 'CK_NEST_MATERIAL', 'MATERIALTYPE IN (''INSULATION_BOX'',''FOOD_BOWL'',''WATER_BOWL'',''OTHER'')');
    add_check('NEST_MAINTENANCERECORDS', 'CK_NEST_WEATHER', 'WEATHERCONDITION IN (''SUNNY'',''CLOUDY'',''RAINY'',''SNOWY'',''OTHER'')');
    add_check('NEST_MAINTENANCERECORDS', 'CK_NEST_DAMAGE', 'DAMAGELEVEL IN (''NONE'',''MINOR'',''MAJOR'')');
    add_check('NEST_MAINTENANCERECORDS', 'CK_NEST_ACTION', 'ACTIONTYPE IN (''CLEAN'',''REPAIR'',''REPLACE'',''OTHER'')');
    add_check('FUND_DONATIONS', 'CK_DONATION_PAY', 'PAYMETHOD IN (''ALIPAY'',''WECHAT'',''BANK_TRANSFER'',''CASH'',''OTHER'')');
    add_check('FUND_FINANCERECORDS', 'CK_FINANCE_RECORD', 'RECORDTYPE IN (''FOOD'',''MEDICAL'',''SUPPLIES'',''OTHER'')');

    COMMIT;
END;
/

PROMPT ===== Field contracts are ready =====;
