SET DEFINE OFF;
SET SERVEROUTPUT ON;
PROMPT ===== Rescue care Oracle programming layer =====;

-- 救助、医疗提醒和失踪预警模块的数据库编程层。
-- C# Repository 查询下方视图，新增和状态流转调用 PKG_RESCUE_CARE。

CREATE OR REPLACE PROCEDURE create_index_if_not_exists(p_sql IN VARCHAR2) AS
BEGIN
    EXECUTE IMMEDIATE p_sql;
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;
/

-- 医疗提醒、紧急救助、失踪预警常用查询索引。
BEGIN
    create_index_if_not_exists('CREATE INDEX IDX_MED_REMINDERS_STATUS_TIME ON MED_REMINDERS(SENDSTATUS, REMINDERTIME)');
    create_index_if_not_exists('CREATE INDEX IDX_MED_REMINDERS_CAT ON MED_REMINDERS(CATID)');
    create_index_if_not_exists('CREATE INDEX IDX_EMERGENCY_STATUS_LEVEL ON EMERGENCY_REPORTS(PROCESSSTATUS, URGENCYLEVEL)');
    create_index_if_not_exists('CREATE INDEX IDX_EMERGENCY_HANDLER ON EMERGENCY_REPORTS(HANDLERUSERID)');
    create_index_if_not_exists('CREATE INDEX IDX_MISSING_STATUS ON CAT_MISSINGALERTS(ALERTSTATUS)');
    create_index_if_not_exists('CREATE INDEX IDX_MISSING_CAT_STATUS ON CAT_MISSINGALERTS(CATID, ALERTSTATUS)');
END;
/

-- 医疗提醒完整视图：提醒列表、按猫查询、按 ID 回查使用。
CREATE OR REPLACE VIEW VW_MED_REMINDERS AS
SELECT R.REMINDERID,
       R.RECORDID,
       R.CATID,
       C.CATNAME,
       R.REMINDERTYPE,
       R.RECEIVERUSERID,
       U.USERNAME AS RECEIVERUSERNAME,
       R.REMINDERTIME,
       NVL(R.SENDSTATUS, 'PENDING') AS SENDSTATUS
FROM MED_REMINDERS R
LEFT JOIN CAT_CATS C ON R.CATID = C.CATID
LEFT JOIN SYS_USERS U ON R.RECEIVERUSERID = U.USERID;
/

-- 医疗提醒待处理视图：提醒中心使用。
CREATE OR REPLACE VIEW VW_MED_PENDING_REMINDERS AS
SELECT REMINDERID,
       RECORDID,
       CATID,
       CATNAME,
       REMINDERTYPE,
       RECEIVERUSERID,
       RECEIVERUSERNAME,
       REMINDERTIME,
       SENDSTATUS
FROM VW_MED_REMINDERS
WHERE SENDSTATUS IN ('PENDING', 'SENT');
/

-- 紧急救助上报视图：管理员和志愿者处理列表使用。
CREATE OR REPLACE VIEW VW_EMERGENCY_REPORTS AS
SELECT E.REPORTID,
       E.REPORTERUSERID,
       RU.USERNAME AS REPORTERUSERNAME,
       E.AREAID,
       A.AREANAME,
       E.ANIMALTYPE,
       E.PHOTOURL,
       E.LONGITUDE,
       E.LATITUDE,
       E.REPORTTIME,
       E.URGENCYLEVEL,
       E.PROCESSSTATUS,
       E.HANDLERUSERID,
       HU.USERNAME AS HANDLERUSERNAME,
       E.PROCESSRESULT
FROM EMERGENCY_REPORTS E
LEFT JOIN SYS_USERS RU ON E.REPORTERUSERID = RU.USERID
LEFT JOIN SYS_USERS HU ON E.HANDLERUSERID = HU.USERID
LEFT JOIN MAP_CAMPUSAREAS A ON E.AREAID = A.AREAID;
/

-- 猫咪失踪预警视图：失踪处理工作台和猫咪详情页使用。
CREATE OR REPLACE VIEW VW_MISSING_ALERTS AS
SELECT M.ALERTID,
       M.CATID,
       C.CATNAME,
       M.LASTSIGHTINGID,
       S.AREAID AS LASTSIGHTINGAREAID,
       A.AREANAME AS LASTSIGHTINGAREANAME,
       M.LASTSIGHTINGTIME,
       M.THRESHOLDDAYS,
       M.ALERTTIME,
       M.ALERTSTATUS,
       M.HANDLERUSERID,
       U.USERNAME AS HANDLERUSERNAME,
       M.CLOSETIME,
       M.REMARK
FROM CAT_MISSINGALERTS M
LEFT JOIN CAT_CATS C ON M.CATID = C.CATID
LEFT JOIN CAT_SIGHTINGS S ON M.LASTSIGHTINGID = S.SIGHTINGID
LEFT JOIN MAP_CAMPUSAREAS A ON S.AREAID = A.AREAID
LEFT JOIN SYS_USERS U ON M.HANDLERUSERID = U.USERID;
/

-- 医疗提醒插入前触发器：补 ID，并统一提醒类型和发送状态。
CREATE OR REPLACE TRIGGER TRG_MED_REMINDERS_BI
BEFORE INSERT ON MED_REMINDERS
FOR EACH ROW
BEGIN
    IF :NEW.REMINDERID IS NULL THEN
        :NEW.REMINDERID := LOWER(RAWTOHEX(SYS_GUID()));
    END IF;

    :NEW.REMINDERTYPE := UPPER(:NEW.REMINDERTYPE);
    :NEW.SENDSTATUS := UPPER(NVL(:NEW.SENDSTATUS, 'PENDING'));
END;
/

-- 医疗提醒更新前触发器：防止大小写不一致影响查询。
CREATE OR REPLACE TRIGGER TRG_MED_REMINDERS_BU
BEFORE UPDATE ON MED_REMINDERS
FOR EACH ROW
BEGIN
    :NEW.REMINDERTYPE := UPPER(:NEW.REMINDERTYPE);
    :NEW.SENDSTATUS := UPPER(:NEW.SENDSTATUS);
END;
/

-- 紧急救助上报插入前触发器：补 ID、上报时间、默认状态，并统一枚举大小写。
CREATE OR REPLACE TRIGGER TRG_EMERGENCY_REPORTS_BI
BEFORE INSERT ON EMERGENCY_REPORTS
FOR EACH ROW
BEGIN
    IF :NEW.REPORTID IS NULL THEN
        :NEW.REPORTID := LOWER(RAWTOHEX(SYS_GUID()));
    END IF;

    IF :NEW.REPORTTIME IS NULL THEN
        :NEW.REPORTTIME := SYSDATE;
    END IF;

    :NEW.URGENCYLEVEL := UPPER(NVL(:NEW.URGENCYLEVEL, 'LOW'));
    :NEW.PROCESSSTATUS := UPPER(NVL(:NEW.PROCESSSTATUS, 'SUBMITTED'));
END;
/

-- 紧急救助上报更新前触发器：统一紧急等级和处理状态大小写。
CREATE OR REPLACE TRIGGER TRG_EMERGENCY_REPORTS_BU
BEFORE UPDATE ON EMERGENCY_REPORTS
FOR EACH ROW
BEGIN
    IF :NEW.URGENCYLEVEL IS NOT NULL THEN
        :NEW.URGENCYLEVEL := UPPER(:NEW.URGENCYLEVEL);
    END IF;

    IF :NEW.PROCESSSTATUS IS NOT NULL THEN
        :NEW.PROCESSSTATUS := UPPER(:NEW.PROCESSSTATUS);
    END IF;
END;
/

-- 失踪预警插入前触发器：补 ID、发布时间和默认处理状态。
CREATE OR REPLACE TRIGGER TRG_CAT_MISSINGALERTS_BI
BEFORE INSERT ON CAT_MISSINGALERTS
FOR EACH ROW
BEGIN
    IF :NEW.ALERTID IS NULL THEN
        :NEW.ALERTID := LOWER(RAWTOHEX(SYS_GUID()));
    END IF;

    IF :NEW.ALERTTIME IS NULL THEN
        :NEW.ALERTTIME := SYSDATE;
    END IF;

    :NEW.ALERTSTATUS := UPPER(NVL(:NEW.ALERTSTATUS, 'PROCESSING'));
END;
/

-- 失踪预警更新前触发器：统一状态，并在寻回或关闭时自动补关闭时间。
CREATE OR REPLACE TRIGGER TRG_CAT_MISSINGALERTS_BU
BEFORE UPDATE ON CAT_MISSINGALERTS
FOR EACH ROW
BEGIN
    IF :NEW.ALERTSTATUS IS NOT NULL THEN
        :NEW.ALERTSTATUS := UPPER(:NEW.ALERTSTATUS);
    END IF;

    IF :NEW.ALERTSTATUS IN ('FOUND', 'CLOSED') AND :NEW.CLOSETIME IS NULL THEN
        :NEW.CLOSETIME := SYSDATE;
    END IF;
END;
/

-- 猫咪目击记录插入前触发器：补 ID 和默认目击时间。
CREATE OR REPLACE TRIGGER TRG_CAT_SIGHTINGS_BI
BEFORE INSERT ON CAT_SIGHTINGS
FOR EACH ROW
BEGIN
    IF :NEW.SIGHTINGID IS NULL THEN
        :NEW.SIGHTINGID := LOWER(RAWTOHEX(SYS_GUID()));
    END IF;

    IF :NEW.SIGHTINGTIME IS NULL THEN
        :NEW.SIGHTINGTIME := SYSDATE;
    END IF;
END;
/

-- 医疗记录插入后触发器：按主分支 MedRecordTypes 契约自动生成后续提醒。
CREATE OR REPLACE TRIGGER TRG_HEALTHRECORDS_AI_REMINDER
AFTER INSERT ON MED_HEALTHRECORDS
FOR EACH ROW
DECLARE
    V_REMINDERTYPE MED_REMINDERS.REMINDERTYPE%TYPE;
BEGIN
    IF :NEW.NEXTDUEDATE IS NULL THEN
        RETURN;
    END IF;

    V_REMINDERTYPE :=
        CASE UPPER(:NEW.RECORDTYPE)
            WHEN 'VACCINATION' THEN 'VACCINATION'
            WHEN 'DEWORMING' THEN 'DEWORMING'
            WHEN 'SURGERY' THEN 'SURGERY'
            WHEN 'CHECKUP' THEN 'CHECKUP'
            WHEN 'TREATMENT' THEN 'TREATMENT'
            WHEN 'EMERGENCY' THEN 'EMERGENCY'
            ELSE 'OTHER'
        END;

    INSERT INTO MED_REMINDERS (
        REMINDERID,
        RECORDID,
        CATID,
        REMINDERTYPE,
        REMINDERTIME,
        SENDSTATUS
    ) VALUES (
        LOWER(RAWTOHEX(SYS_GUID())),
        :NEW.RECORDID,
        :NEW.CATID,
        V_REMINDERTYPE,
        :NEW.NEXTDUEDATE,
        'PENDING'
    );
END;
/

-- 救助护理流程包：供 C# Repository 调用。
CREATE OR REPLACE PACKAGE PKG_RESCUE_CARE AS
    PROCEDURE CREATE_REMINDER(
        P_RECORDID       IN MED_REMINDERS.RECORDID%TYPE,
        P_CATID          IN MED_REMINDERS.CATID%TYPE,
        P_REMINDERTYPE   IN MED_REMINDERS.REMINDERTYPE%TYPE,
        P_RECEIVERUSERID IN MED_REMINDERS.RECEIVERUSERID%TYPE,
        P_REMINDERTIME   IN MED_REMINDERS.REMINDERTIME%TYPE,
        O_REMINDERID     OUT MED_REMINDERS.REMINDERID%TYPE
    );

    PROCEDURE MARK_REMINDER_SENT(P_REMINDERID IN MED_REMINDERS.REMINDERID%TYPE);
    PROCEDURE COMPLETE_REMINDER(P_REMINDERID IN MED_REMINDERS.REMINDERID%TYPE);

    PROCEDURE SUBMIT_EMERGENCY_REPORT(
        P_REPORTERUSERID IN EMERGENCY_REPORTS.REPORTERUSERID%TYPE,
        P_AREAID         IN EMERGENCY_REPORTS.AREAID%TYPE,
        P_ANIMALTYPE     IN EMERGENCY_REPORTS.ANIMALTYPE%TYPE,
        P_PHOTOURL       IN EMERGENCY_REPORTS.PHOTOURL%TYPE,
        P_LONGITUDE      IN EMERGENCY_REPORTS.LONGITUDE%TYPE,
        P_LATITUDE       IN EMERGENCY_REPORTS.LATITUDE%TYPE,
        P_URGENCYLEVEL   IN EMERGENCY_REPORTS.URGENCYLEVEL%TYPE,
        O_REPORTID       OUT EMERGENCY_REPORTS.REPORTID%TYPE
    );

    PROCEDURE ASSIGN_EMERGENCY_REPORT(
        P_REPORTID      IN EMERGENCY_REPORTS.REPORTID%TYPE,
        P_HANDLERUSERID IN EMERGENCY_REPORTS.HANDLERUSERID%TYPE
    );

    PROCEDURE UPDATE_EMERGENCY_STATUS(
        P_REPORTID      IN EMERGENCY_REPORTS.REPORTID%TYPE,
        P_PROCESSSTATUS IN EMERGENCY_REPORTS.PROCESSSTATUS%TYPE,
        P_PROCESSRESULT IN EMERGENCY_REPORTS.PROCESSRESULT%TYPE
    );

    PROCEDURE CREATE_SIGHTING(
        P_CATID        IN CAT_SIGHTINGS.CATID%TYPE,
        P_USERID       IN CAT_SIGHTINGS.USERID%TYPE,
        P_AREAID       IN CAT_SIGHTINGS.AREAID%TYPE,
        P_LONGITUDE    IN CAT_SIGHTINGS.LONGITUDE%TYPE,
        P_LATITUDE     IN CAT_SIGHTINGS.LATITUDE%TYPE,
        P_PHOTOURL     IN CAT_SIGHTINGS.PHOTOURL%TYPE,
        P_SIGHTINGTIME IN CAT_SIGHTINGS.SIGHTINGTIME%TYPE,
        P_REMARK       IN CAT_SIGHTINGS.REMARK%TYPE,
        O_SIGHTINGID   OUT CAT_SIGHTINGS.SIGHTINGID%TYPE
    );

    PROCEDURE CREATE_MISSING_ALERT(
        P_CATID            IN CAT_MISSINGALERTS.CATID%TYPE,
        P_LASTSIGHTINGID   IN CAT_MISSINGALERTS.LASTSIGHTINGID%TYPE,
        P_LASTSIGHTINGTIME IN CAT_MISSINGALERTS.LASTSIGHTINGTIME%TYPE,
        P_THRESHOLDDAYS    IN CAT_MISSINGALERTS.THRESHOLDDAYS%TYPE,
        P_HANDLERUSERID    IN CAT_MISSINGALERTS.HANDLERUSERID%TYPE,
        P_REMARK           IN CAT_MISSINGALERTS.REMARK%TYPE,
        O_ALERTID          OUT CAT_MISSINGALERTS.ALERTID%TYPE
    );

    PROCEDURE UPDATE_MISSING_STATUS(
        P_ALERTID       IN CAT_MISSINGALERTS.ALERTID%TYPE,
        P_ALERTSTATUS   IN CAT_MISSINGALERTS.ALERTSTATUS%TYPE,
        P_HANDLERUSERID IN CAT_MISSINGALERTS.HANDLERUSERID%TYPE,
        P_REMARK        IN CAT_MISSINGALERTS.REMARK%TYPE
    );

    PROCEDURE AUTO_CREATE_REMINDERS_FROM_HEALTH;
END PKG_RESCUE_CARE;
/

SHOW ERRORS PACKAGE PKG_RESCUE_CARE

CREATE OR REPLACE PACKAGE BODY PKG_RESCUE_CARE AS
    FUNCTION NEW_ID RETURN VARCHAR2 AS
    BEGIN
        RETURN LOWER(RAWTOHEX(SYS_GUID()));
    END NEW_ID;

    PROCEDURE ASSERT_NOT_BLANK(P_VALUE IN VARCHAR2, P_ERROR_CODE IN NUMBER, P_ERROR_MESSAGE IN VARCHAR2) AS
    BEGIN
        IF P_VALUE IS NULL OR TRIM(P_VALUE) IS NULL THEN
            RAISE_APPLICATION_ERROR(P_ERROR_CODE, P_ERROR_MESSAGE);
        END IF;
    END ASSERT_NOT_BLANK;

    PROCEDURE ASSERT_STATUS(P_VALUE IN VARCHAR2, P_ALLOWED IN VARCHAR2, P_ERROR_CODE IN NUMBER, P_ERROR_MESSAGE IN VARCHAR2) AS
    BEGIN
        IF P_VALUE IS NULL OR INSTR(',' || P_ALLOWED || ',', ',' || P_VALUE || ',') = 0 THEN
            RAISE_APPLICATION_ERROR(P_ERROR_CODE, P_ERROR_MESSAGE || ': ' || NVL(P_VALUE, '<NULL>'));
        END IF;
    END ASSERT_STATUS;

    PROCEDURE CREATE_REMINDER(
        P_RECORDID       IN MED_REMINDERS.RECORDID%TYPE,
        P_CATID          IN MED_REMINDERS.CATID%TYPE,
        P_REMINDERTYPE   IN MED_REMINDERS.REMINDERTYPE%TYPE,
        P_RECEIVERUSERID IN MED_REMINDERS.RECEIVERUSERID%TYPE,
        P_REMINDERTIME   IN MED_REMINDERS.REMINDERTIME%TYPE,
        O_REMINDERID     OUT MED_REMINDERS.REMINDERID%TYPE
    ) AS
        V_RECORD_COUNT NUMBER;
    BEGIN
        ASSERT_NOT_BLANK(P_CATID, -20120, 'Cat id is required');
        ASSERT_NOT_BLANK(P_REMINDERTYPE, -20121, 'Reminder type is required');

        IF P_RECORDID IS NOT NULL THEN
            SELECT COUNT(1) INTO V_RECORD_COUNT
            FROM MED_HEALTHRECORDS
            WHERE RECORDID = P_RECORDID AND CATID = P_CATID;
            IF V_RECORD_COUNT = 0 THEN
                RAISE_APPLICATION_ERROR(-20128, 'Medical record does not belong to the specified cat');
            END IF;
        END IF;

        IF P_REMINDERTIME IS NULL THEN
            RAISE_APPLICATION_ERROR(-20122, 'Reminder time is required');
        END IF;

        ASSERT_STATUS(
            UPPER(P_REMINDERTYPE),
            'VACCINATION,CHECKUP,TREATMENT,SURGERY,DEWORMING,EMERGENCY,OTHER',
            -20123,
            'Invalid reminder type'
        );

        O_REMINDERID := NEW_ID();

        INSERT INTO MED_REMINDERS (
            REMINDERID,
            RECORDID,
            CATID,
            REMINDERTYPE,
            RECEIVERUSERID,
            REMINDERTIME,
            SENDSTATUS
        ) VALUES (
            O_REMINDERID,
            P_RECORDID,
            P_CATID,
            UPPER(P_REMINDERTYPE),
            P_RECEIVERUSERID,
            P_REMINDERTIME,
            'PENDING'
        );
    END CREATE_REMINDER;

    PROCEDURE MARK_REMINDER_SENT(P_REMINDERID IN MED_REMINDERS.REMINDERID%TYPE) AS
    BEGIN
        ASSERT_NOT_BLANK(P_REMINDERID, -20124, 'Reminder id is required');

        UPDATE MED_REMINDERS
        SET SENDSTATUS = 'SENT'
        WHERE REMINDERID = P_REMINDERID;

        IF SQL%ROWCOUNT = 0 THEN
            RAISE_APPLICATION_ERROR(-20125, 'Reminder not found');
        END IF;
    END MARK_REMINDER_SENT;

    PROCEDURE COMPLETE_REMINDER(P_REMINDERID IN MED_REMINDERS.REMINDERID%TYPE) AS
    BEGIN
        ASSERT_NOT_BLANK(P_REMINDERID, -20126, 'Reminder id is required');

        UPDATE MED_REMINDERS
        SET SENDSTATUS = 'COMPLETED'
        WHERE REMINDERID = P_REMINDERID;

        IF SQL%ROWCOUNT = 0 THEN
            RAISE_APPLICATION_ERROR(-20127, 'Reminder not found');
        END IF;
    END COMPLETE_REMINDER;

    PROCEDURE SUBMIT_EMERGENCY_REPORT(
        P_REPORTERUSERID IN EMERGENCY_REPORTS.REPORTERUSERID%TYPE,
        P_AREAID         IN EMERGENCY_REPORTS.AREAID%TYPE,
        P_ANIMALTYPE     IN EMERGENCY_REPORTS.ANIMALTYPE%TYPE,
        P_PHOTOURL       IN EMERGENCY_REPORTS.PHOTOURL%TYPE,
        P_LONGITUDE      IN EMERGENCY_REPORTS.LONGITUDE%TYPE,
        P_LATITUDE       IN EMERGENCY_REPORTS.LATITUDE%TYPE,
        P_URGENCYLEVEL   IN EMERGENCY_REPORTS.URGENCYLEVEL%TYPE,
        O_REPORTID       OUT EMERGENCY_REPORTS.REPORTID%TYPE
    ) AS
    BEGIN
        ASSERT_NOT_BLANK(P_REPORTERUSERID, -20130, 'Reporter user id is required');
        ASSERT_NOT_BLANK(P_AREAID, -20131, 'Area id is required');
        ASSERT_NOT_BLANK(P_ANIMALTYPE, -20132, 'Animal type is required');
        ASSERT_NOT_BLANK(P_URGENCYLEVEL, -20133, 'Urgency level is required');
        ASSERT_STATUS(UPPER(P_URGENCYLEVEL), 'LOW,MEDIUM,HIGH,CRITICAL', -20134, 'Invalid urgency level');

        O_REPORTID := NEW_ID();

        INSERT INTO EMERGENCY_REPORTS (
            REPORTID,
            REPORTERUSERID,
            AREAID,
            ANIMALTYPE,
            PHOTOURL,
            LONGITUDE,
            LATITUDE,
            REPORTTIME,
            URGENCYLEVEL,
            PROCESSSTATUS
        ) VALUES (
            O_REPORTID,
            P_REPORTERUSERID,
            P_AREAID,
            P_ANIMALTYPE,
            P_PHOTOURL,
            P_LONGITUDE,
            P_LATITUDE,
            SYSDATE,
            UPPER(P_URGENCYLEVEL),
            'SUBMITTED'
        );
    END SUBMIT_EMERGENCY_REPORT;

    PROCEDURE ASSIGN_EMERGENCY_REPORT(
        P_REPORTID      IN EMERGENCY_REPORTS.REPORTID%TYPE,
        P_HANDLERUSERID IN EMERGENCY_REPORTS.HANDLERUSERID%TYPE
    ) AS
    BEGIN
        ASSERT_NOT_BLANK(P_REPORTID, -20135, 'Emergency report id is required');
        ASSERT_NOT_BLANK(P_HANDLERUSERID, -20136, 'Handler user id is required');

        UPDATE EMERGENCY_REPORTS
        SET HANDLERUSERID = P_HANDLERUSERID,
            PROCESSSTATUS = 'ASSIGNED'
        WHERE REPORTID = P_REPORTID;

        IF SQL%ROWCOUNT = 0 THEN
            RAISE_APPLICATION_ERROR(-20137, 'Emergency report not found');
        END IF;
    END ASSIGN_EMERGENCY_REPORT;

    PROCEDURE UPDATE_EMERGENCY_STATUS(
        P_REPORTID      IN EMERGENCY_REPORTS.REPORTID%TYPE,
        P_PROCESSSTATUS IN EMERGENCY_REPORTS.PROCESSSTATUS%TYPE,
        P_PROCESSRESULT IN EMERGENCY_REPORTS.PROCESSRESULT%TYPE
    ) AS
    BEGIN
        ASSERT_NOT_BLANK(P_REPORTID, -20138, 'Emergency report id is required');
        ASSERT_NOT_BLANK(P_PROCESSSTATUS, -20139, 'Process status is required');
        ASSERT_STATUS(UPPER(P_PROCESSSTATUS), 'SUBMITTED,ASSIGNED,PROCESSING,RESOLVED,CLOSED', -20140, 'Invalid process status');

        UPDATE EMERGENCY_REPORTS
        SET PROCESSSTATUS = UPPER(P_PROCESSSTATUS),
            PROCESSRESULT = P_PROCESSRESULT
        WHERE REPORTID = P_REPORTID;

        IF SQL%ROWCOUNT = 0 THEN
            RAISE_APPLICATION_ERROR(-20141, 'Emergency report not found');
        END IF;
    END UPDATE_EMERGENCY_STATUS;

    PROCEDURE CREATE_SIGHTING(
        P_CATID        IN CAT_SIGHTINGS.CATID%TYPE,
        P_USERID       IN CAT_SIGHTINGS.USERID%TYPE,
        P_AREAID       IN CAT_SIGHTINGS.AREAID%TYPE,
        P_LONGITUDE    IN CAT_SIGHTINGS.LONGITUDE%TYPE,
        P_LATITUDE     IN CAT_SIGHTINGS.LATITUDE%TYPE,
        P_PHOTOURL     IN CAT_SIGHTINGS.PHOTOURL%TYPE,
        P_SIGHTINGTIME IN CAT_SIGHTINGS.SIGHTINGTIME%TYPE,
        P_REMARK       IN CAT_SIGHTINGS.REMARK%TYPE,
        O_SIGHTINGID   OUT CAT_SIGHTINGS.SIGHTINGID%TYPE
    ) AS
    BEGIN
        ASSERT_NOT_BLANK(P_CATID, -20150, 'Cat id is required');
        ASSERT_NOT_BLANK(P_AREAID, -20151, 'Area id is required');

        IF P_SIGHTINGTIME IS NULL THEN
            RAISE_APPLICATION_ERROR(-20152, 'Sighting time is required');
        END IF;

        O_SIGHTINGID := NEW_ID();

        INSERT INTO CAT_SIGHTINGS (
            SIGHTINGID,
            CATID,
            USERID,
            AREAID,
            LONGITUDE,
            LATITUDE,
            PHOTOURL,
            SIGHTINGTIME,
            REMARK
        ) VALUES (
            O_SIGHTINGID,
            P_CATID,
            P_USERID,
            P_AREAID,
            P_LONGITUDE,
            P_LATITUDE,
            P_PHOTOURL,
            P_SIGHTINGTIME,
            P_REMARK
        );
    END CREATE_SIGHTING;

    PROCEDURE CREATE_MISSING_ALERT(
        P_CATID            IN CAT_MISSINGALERTS.CATID%TYPE,
        P_LASTSIGHTINGID   IN CAT_MISSINGALERTS.LASTSIGHTINGID%TYPE,
        P_LASTSIGHTINGTIME IN CAT_MISSINGALERTS.LASTSIGHTINGTIME%TYPE,
        P_THRESHOLDDAYS    IN CAT_MISSINGALERTS.THRESHOLDDAYS%TYPE,
        P_HANDLERUSERID    IN CAT_MISSINGALERTS.HANDLERUSERID%TYPE,
        P_REMARK           IN CAT_MISSINGALERTS.REMARK%TYPE,
        O_ALERTID          OUT CAT_MISSINGALERTS.ALERTID%TYPE
    ) AS
        V_SIGHTING_COUNT NUMBER;
        V_ACTIVE_ALERT_COUNT NUMBER;
    BEGIN
        ASSERT_NOT_BLANK(P_CATID, -20160, 'Cat id is required');

        IF P_LASTSIGHTINGID IS NOT NULL THEN
            SELECT COUNT(1) INTO V_SIGHTING_COUNT
            FROM CAT_SIGHTINGS
            WHERE SIGHTINGID = P_LASTSIGHTINGID AND CATID = P_CATID;
            IF V_SIGHTING_COUNT = 0 THEN
                RAISE_APPLICATION_ERROR(-20162, 'Last sighting does not belong to the specified cat');
            END IF;
        END IF;

        SELECT COUNT(1) INTO V_ACTIVE_ALERT_COUNT
        FROM CAT_MISSINGALERTS
        WHERE CATID = P_CATID AND UPPER(ALERTSTATUS) = 'PROCESSING';
        IF V_ACTIVE_ALERT_COUNT > 0 THEN
            RAISE_APPLICATION_ERROR(-20163, 'The cat already has an active missing alert');
        END IF;

        IF P_THRESHOLDDAYS IS NOT NULL AND P_THRESHOLDDAYS <= 0 THEN
            RAISE_APPLICATION_ERROR(-20161, 'Threshold days must be greater than 0');
        END IF;

        O_ALERTID := NEW_ID();

        INSERT INTO CAT_MISSINGALERTS (
            ALERTID,
            CATID,
            LASTSIGHTINGID,
            LASTSIGHTINGTIME,
            THRESHOLDDAYS,
            ALERTTIME,
            ALERTSTATUS,
            HANDLERUSERID,
            REMARK
        ) VALUES (
            O_ALERTID,
            P_CATID,
            P_LASTSIGHTINGID,
            P_LASTSIGHTINGTIME,
            P_THRESHOLDDAYS,
            SYSDATE,
            'PROCESSING',
            P_HANDLERUSERID,
            P_REMARK
        );
    END CREATE_MISSING_ALERT;

    PROCEDURE UPDATE_MISSING_STATUS(
        P_ALERTID       IN CAT_MISSINGALERTS.ALERTID%TYPE,
        P_ALERTSTATUS   IN CAT_MISSINGALERTS.ALERTSTATUS%TYPE,
        P_HANDLERUSERID IN CAT_MISSINGALERTS.HANDLERUSERID%TYPE,
        P_REMARK        IN CAT_MISSINGALERTS.REMARK%TYPE
    ) AS
    BEGIN
        ASSERT_NOT_BLANK(P_ALERTID, -20170, 'Missing alert id is required');
        ASSERT_NOT_BLANK(P_ALERTSTATUS, -20171, 'Missing alert status is required');
        ASSERT_NOT_BLANK(P_HANDLERUSERID, -20172, 'Handler user id is required');
        ASSERT_STATUS(UPPER(P_ALERTSTATUS), 'PROCESSING,FOUND,CLOSED', -20173, 'Invalid missing alert status');

        UPDATE CAT_MISSINGALERTS
        SET ALERTSTATUS = UPPER(P_ALERTSTATUS),
            HANDLERUSERID = P_HANDLERUSERID,
            REMARK = NVL(P_REMARK, REMARK),
            CLOSETIME = CASE
                WHEN UPPER(P_ALERTSTATUS) IN ('FOUND', 'CLOSED') THEN SYSDATE
                ELSE CLOSETIME
            END
        WHERE ALERTID = P_ALERTID;

        IF SQL%ROWCOUNT = 0 THEN
            RAISE_APPLICATION_ERROR(-20174, 'Missing alert not found');
        END IF;
    END UPDATE_MISSING_STATUS;

    PROCEDURE AUTO_CREATE_REMINDERS_FROM_HEALTH AS
    BEGIN
        INSERT INTO MED_REMINDERS (
            REMINDERID,
            RECORDID,
            CATID,
            REMINDERTYPE,
            REMINDERTIME,
            SENDSTATUS
        )
        SELECT LOWER(RAWTOHEX(SYS_GUID())),
               H.RECORDID,
               H.CATID,
               CASE UPPER(H.RECORDTYPE)
                   WHEN 'VACCINATION' THEN 'VACCINATION'
                   WHEN 'DEWORMING' THEN 'DEWORMING'
                   WHEN 'SURGERY' THEN 'SURGERY'
                   WHEN 'CHECKUP' THEN 'CHECKUP'
                   WHEN 'TREATMENT' THEN 'TREATMENT'
                   WHEN 'EMERGENCY' THEN 'EMERGENCY'
                   ELSE 'OTHER'
               END,
               H.NEXTDUEDATE,
               'PENDING'
        FROM MED_HEALTHRECORDS H
        WHERE H.NEXTDUEDATE IS NOT NULL
          AND NOT EXISTS (
              SELECT 1
              FROM MED_REMINDERS R
              WHERE R.RECORDID = H.RECORDID
          );
    END AUTO_CREATE_REMINDERS_FROM_HEALTH;
END PKG_RESCUE_CARE;
/

SHOW ERRORS PACKAGE BODY PKG_RESCUE_CARE

PROMPT Rescue care Oracle programming layer completed. Please execute this script after create_tables.sql.
